-- Imported Mvuma Holy Land pledge records.
-- Review records marked "Name pending" and edit missing details in the Pledges screen.
-- Run supabase_pledges_setup.sql first.

insert into public.pledges (id, owner_key, name, phone, email, branch, pledge_type, amount, materials, notes, status) values
('import-pledge-001', '', 'Chiremba Rumbi', '', '', 'Bikita Masvingo', 'Money', '', '', 'Masvingo Province chairlady. Objective: fish project and restaurant. Subject: raising money to build an office at Mvuma Holy Land. Shrine name pending.', 'New'),
('import-pledge-002', '', 'Name pending', '', '', 'Gokwe', 'Money', '', '', 'Objective: restaurant for traditional food.', 'New'),
('import-pledge-003', '', 'Name pending', '', '', 'Gokwe', 'Money', '', '', 'Chairlady province. Objective: mining inside land given by Mambo Gwesela and farming as well.', 'New'),
('import-pledge-004', '', 'Name pending', '', '', 'Harare Metropolitan', 'Materials', '', '10 bags of cement', 'Position: Elder. Objective: cement for Holy Land development.', 'New'),
('import-pledge-005', '', 'Amai Mudzingwa', '', '', 'Mabvuku', 'Materials', '', '100 bags of cement', '', 'New'),
('import-pledge-006', '', 'Name pending', '', '', 'Mashwest', 'Materials', '', '1 bag of cement', 'Objective: encourages Ruvadzano to bring a bag of cement for Mvuma Holy Land Development. Position pending.', 'New'),
('import-pledge-007', '', 'Blessing', '', '', 'Mashwest', 'Materials', '', 'Manpower', 'Position: Secretary. Objective: pledges manpower for Holy Land Development.', 'New'),
('import-pledge-008', '', 'Amai Tsitsi', '', '', 'Mash East Mutoko', 'Materials', '', '100 bags of cement', 'Position: Provincial Treasurer. Objective: encourage Ruvadzano and carry the church forward; speaks on offer letter for J5 Holy Land.', 'New'),
('import-pledge-009', '', 'Amai Sigauke', '', '', 'Mutoko', 'Materials', '', '10 bags of cement', 'Position: Provincial chair leader. Objective: church rebuilding and starts the challenge.', 'New'),
('import-pledge-010', '', 'Nyasha Tembo', '', '', 'Chinhoyi', 'Materials', '', '20 bags of cement', 'Challenge pledge.', 'New'),
('import-pledge-011', '', 'Mutokoza', '', '', 'Gwanda C', 'Materials', '', '30 bags of cement', 'Challenge pledge.', 'New'),
('import-pledge-012', '', 'Gogo Sithole', '', '', 'Masvingo', 'Materials', '', '60 bags of cement', 'Challenge pledge.', 'New'),
('import-pledge-013', '', 'Farai Dube', '', '', 'Harare', 'Materials', '', '35 bags of cement', 'Challenge pledge.', 'New'),
('import-pledge-014', '', 'Nontokozo', '', '', 'Gwanda C', 'Materials', '', '30 bags of cement', '', 'New'),
('import-pledge-015', '', 'Chighomba', '', '', 'Zvishavane', 'Materials', '', '40 bags of cement', '', 'New'),
('import-pledge-016', '', 'Percevearance Masahwa', '', '', 'Beitbridge', 'Materials', '', '', 'Pledge detail missing.', 'New'),
('import-pledge-017', '', 'Ireen Perego', '', '', 'Chinhoyi A', 'Materials', '', '10 bags of cement', '', 'New'),
('import-pledge-018', '', 'Amai Ruth', '', '', '4 Miles Zvishavane', 'Materials', '', '', 'Pledge detail missing.', 'New'),
('import-pledge-019', '', 'Shamiso Zhombe', '', '', 'Zhombe', 'Materials', '', '12 bags of cement', '', 'New'),
('import-pledge-020', '', 'Amai Juliet', '', '', 'Masvingo Mberengwa York', 'Materials', '', '15 bags of cement', '', 'New'),
('import-pledge-021', '', 'Matutu Silence', '', '', 'Ngundu Masvingo', 'Materials', '', '15 bags of cement', '', 'New'),
('import-pledge-022', '', 'Rejoice', '', '', 'Midlands Jombe', 'Materials', '', '15 bags', 'Material type pending.', 'New'),
('import-pledge-023', '', 'Fungai Mbano', '', '', 'Shurugwi Canaan', 'Materials', '', '', 'Pledge detail missing.', 'New'),
('import-pledge-024', '', 'Patience Shurugwi', '', '', 'Midlands', 'Materials', '', '5 bags', 'Material type pending.', 'New'),
('import-pledge-025', '', 'Dorica Mostaf', '', '', 'Not supplied', 'Materials', '', '5 bags of cement', 'Testimony: answered prayer for building J5.', 'New'),
('import-pledge-026', '', 'Shila Ganyani', '', '', 'Zimuko', 'Materials', '', '6 bags', 'Material type pending.', 'New'),
('import-pledge-027', '', 'Martha Mugwenu', '', '', 'Chiby Turnoff', 'Materials', '', '5 bags of cement', '', 'New'),
('import-pledge-028', '', 'Gladis Makamba', '', '', 'Rutenga Branch', 'Materials', '', '5 bags of cement', 'Not a challenge; refuses to stay behind as a lady.', 'New'),
('import-pledge-029', '', 'Shupikai Michelle', '', '', 'Canaan', 'Materials', '', '5 bags of cement', '', 'New'),
('import-pledge-030', '', 'Mai Restina', '', '', 'Masvingo', 'Materials', '', '5 marata, 12 ft', 'Refuses to copy others. Confirm exact material spelling and quantity.', 'New'),
('import-pledge-031', '', 'Livinia Dube', '', '', '4 Miles Zvishavane', 'Materials', '', '12 ft marata', '', 'New'),
('import-pledge-032', '', 'Linnet Dube', '', '', 'Gwanda Hantinya', 'Money', '100 USD', '', '', 'New'),
('import-pledge-033', '', 'Lilian Chaka Ruchanyo', '', '', 'Pendows Midlands', 'Materials', '', '10 marata, 12 ft', 'Confirm exact material spelling.', 'New'),
('import-pledge-034', '', 'Effy', '', '', 'Masvingo Jerusalema A', 'Materials', '', '12 marata', '', 'New'),
('import-pledge-035', '', 'Muwani Mugowa Joina', '', '', 'Midlands', 'Materials', '', '5 bags of cement', '', 'New'),
('import-pledge-036', '', 'Mugorowoni Gamechanger', '', '', 'Bulawayo', 'Materials', '', '6 bags of cement', '', 'New'),
('import-pledge-037', '', 'Linda', '', '', 'White House Harare', 'Materials', '', '5 bags of cement', 'Position: Secretary for District.', 'New'),
('import-pledge-038', '', 'Wini Mangwadu', '', '', 'White House Harare', 'Materials', '', '2000 bricks', 'Position: Chairlady.', 'New'),
('import-pledge-039', '', 'Ronika Shoko', '', '', 'White House Harare', 'Money', '120 USD equivalent', 'Full load of pit sand', 'Confirm whether this should be recorded as materials or money equivalent.', 'New'),
('import-pledge-040', '', 'Media Makume', '', '', 'White House Harare', 'Materials', '', '7 cubic pit sand', '', 'New'),
('import-pledge-041', '', 'Tinenyahsa', '', '', 'Mbizo A Kwekwe', 'Materials', '', '6 bags of cement', 'Originally 2 bags on 24 August, adding 4 more. Also location note: Zhombe.', 'New'),
('import-pledge-042', '', 'Grace', '', '', 'Zhombe', 'Materials', '', 'Farm bricks', 'Name supplied as Grace in the note; confirm full name.', 'New'),
('import-pledge-043', '', 'Mavis Tagwireyi', '', '', 'Zhombe', 'Materials', '', '250 bricks', '', 'New'),
('import-pledge-044', '', 'Name pending', '', '', 'Mash Central', 'Materials', '', '100 Brick Force wire', '', 'New'),
('import-pledge-045', '', 'Spatisiwe Ncube', '', '', 'Midlands', 'Materials', '', '10 boxes of tiles', '', 'New'),
('import-pledge-046', '', 'Beatrice Masaire', '', '', 'Gutu Masvingo', 'Materials', '', '11 boxes of tiles', 'Position: Vice Chair.', 'New'),
('import-pledge-047', '', 'Mercy Rashai', '', '', 'Not supplied', 'Materials', '', '15 boxes of tiles', 'Location pending.', 'New'),
('import-pledge-048', '', 'Sarah Chimunhu', '', '', 'Harare', 'Materials', '', '1 load of pit sand', '', 'New'),
('import-pledge-049', '', 'Emma Mhosva', '', '', 'Chisawasa', 'Materials', '', '1 load of pit sand', '', 'New'),
('import-pledge-050', '', 'Prophecy Getty', '', '', 'Holy Land', 'Materials', '', '15 boxes of tiles', 'Position supplied as: Prophetecy Getty.', 'New'),
('import-pledge-051', '', 'Chiremba Gabriel', '', '', 'Not supplied', 'Materials', '', '15 boxes of tiles', '', 'New'),
('import-pledge-052', '', 'Linnet Dube', '', '', 'Bulawayo', 'Materials', '', '15 boxes of tiles', '', 'New'),
('import-pledge-053', '', 'Gwanda Hwanyima', '', '', 'Mash South', 'Money', '100 USD', '', '', 'New'),
('import-pledge-054', '', 'Katsande', '', '', 'Mash Central', 'Materials', '', '10 boxes of tiles', '', 'New'),
('import-pledge-055', '', 'Name pending', '', '', 'Not supplied', 'Materials', '', '5 drums', 'Joined venture: 2 Prophecy participants. Names pending.', 'New'),
('import-pledge-056', '', 'Ncube Sibusiso', '', '', 'Not supplied', 'Materials', '', '20 Brick Force wire', '', 'New'),
('import-pledge-057', '', 'Netsai Zuze', '', '', 'Not supplied', 'Money', '70 USD', '', '', 'New'),
('import-pledge-058', '', 'Taiziwei Moyana', '', '', 'Not supplied', 'Money', '50 USD', '', '', 'New'),
('import-pledge-059', '', 'Zulu', '', '', 'Mashwest', 'Money', '50 USD', '1 bag of cement', 'Combined money and materials pledge.', 'New'),
('import-pledge-060', '', 'Junior Lupungo', '', '', 'Not supplied', 'Materials', '', '200 air bricks', 'Material recorded as air bricks; confirm wording.', 'New'),
('import-pledge-061', '', 'Name pending', '', '', 'Mbizo and Amavhenu', 'Materials', '', '1 load of pit sand', 'Joined venture: 2 chairladies. Names pending.', 'New'),
('import-pledge-062', '', 'Kudzai Nyamazhombe', '', '', 'Not supplied', 'Money', '100 USD', '', '', 'New'),
('import-pledge-063', '', 'Teurai', '', '', 'Not supplied', 'Money', '50 USD', '', '', 'New'),
('import-pledge-064', '', 'Chiremba Grace', '', '', 'Not supplied', 'Materials', '', '19 bags of cement', '', 'New'),
('import-pledge-065', '', 'Name pending', '', '', 'Midlands', 'Materials', '', '15 bags of tylone', 'Position: Chairlady Midlands. Confirm material spelling.', 'New'),
('import-pledge-066', '', 'Mbuya Nyandoro', '', '', 'Masvingo Province', 'Materials', '', '2 mafoshoro', 'Confirm material spelling.', 'New'),
('import-pledge-067', '', 'Amai Miriam', '', '', 'Midlands', 'Money', '50 USD', '', '', 'New'),
('import-pledge-068', '', 'Name pending', '', '', 'Midlands', 'Materials', '', '2 bags of cement plus 10 bags of tylone', 'Joined venture: 3 priestesses from Midlands. Pledged on 24 August. Names pending; confirm material spelling.', 'New'),
('import-pledge-069', '', 'Gogo Chafute', '', '', 'Mash South', 'Money', '20 USD', '', '', 'New'),
('import-pledge-070', '', 'Letwin Mombedzi', '', '', 'Harare Boka', 'Materials', '', '5 door frames', '', 'New'),
('import-pledge-071', '', 'Isabel', '', '', 'Zvishavane 4 Miles', 'Money', '50 USD', '', '', 'New'),
('import-pledge-072', '', 'Name pending', '', '', 'Rutenga Masvingo Province', 'Materials', '', '100 litres of paint in 20 litre containers', 'Joined venture: 2 sisters, both chairladies. Names pending.', 'New'),
('import-pledge-073', '', 'Name pending', '', '', 'Mashwest', 'Money', '50 USD', '','Name pending.', 'New'),
('import-pledge-074', '', 'Name pending', '', '', 'Beitbridge', 'Money', '50 USD', '', 'Location supplied without name.', 'New'),
('import-pledge-075', '', 'Name pending', '', '', 'Mbizo Kwekwe', 'Materials', '', '10 bags of grout', 'Location spelling supplied as Bizob Kwekwe in note.', 'New'),
('import-pledge-076', '', 'Name pending', '', '', 'Chigomba', 'Materials', '', '10 peaks', 'Confirm material spelling.', 'New'),
('import-pledge-077', '', 'Majuru', '', '', 'Goromonzi', 'Money', '25 USD', '', '', 'New'),
('import-pledge-078', '', 'Mother Adviser and Father Adviser', '', '', 'Not supplied', 'Materials', '', '3000 bricks and 5 wheelbarrows', '', 'New')
on conflict (id) do nothing;
