-- Extracted from MASVINGO.pdf.
-- These are branch Treasurer and Secretary contacts, not prophet assignments.
-- Review the schema and run in Supabase SQL Editor.

create table if not exists public.branch_contacts (
  id text primary key,
  branch_id text,
  branch_name text not null,
  province text not null default 'MASVINGO',
  role text not null,
  name text not null default '',
  phone text not null default '',
  source text not null default ''
);

insert into public.branch_contacts
  (id, branch_id, branch_name, province, role, name, phone, source)
values
  ('masvingo-contact-001', (select id from public.branches where upper(name) = 'MASVINGO C' and upper(country) = 'ZIMBABWE' limit 1), 'MASVINGO C', 'MASVINGO', 'Secretary', 'Noster Mukoki', '0789746713', 'MASVINGO.pdf'),
  ('masvingo-contact-002', (select id from public.branches where upper(name) = 'MANYAMA' and upper(country) = 'ZIMBABWE' limit 1), 'MANYAMA', 'MASVINGO', 'Treasurer', 'Judith Maturure', '0779463390', 'MASVINGO.pdf'),
  ('masvingo-contact-003', (select id from public.branches where upper(name) = 'MANYAMA' and upper(country) = 'ZIMBABWE' limit 1), 'MANYAMA', 'MASVINGO', 'Secretary', 'Tendai Nyamadzawo', '0771571262', 'MASVINGO.pdf'),
  ('masvingo-contact-004', (select id from public.branches where upper(name) = 'MASVINGO B' and upper(country) = 'ZIMBABWE' limit 1), 'MASVINGO B', 'MASVINGO', 'Treasurer', 'Confidence Mutsvanga', '0784577140', 'MASVINGO.pdf'),
  ('masvingo-contact-005', (select id from public.branches where upper(name) = 'MASVINGO B' and upper(country) = 'ZIMBABWE' limit 1), 'MASVINGO B', 'MASVINGO', 'Secretary', 'Nomalanga Togarepi', '0773606221', 'MASVINGO.pdf'),
  ('masvingo-contact-006', (select id from public.branches where upper(name) = 'MASVINGO A' and upper(country) = 'ZIMBABWE' limit 1), 'MASVINGO A', 'MASVINGO', 'Treasurer', 'Verna Nyazire', '0718948135/0773908385', 'MASVINGO.pdf'),
  ('masvingo-contact-007', (select id from public.branches where upper(name) = 'MASVINGO A' and upper(country) = 'ZIMBABWE' limit 1), 'MASVINGO A', 'MASVINGO', 'Secretary', 'Regina Mukanyangi', '0784685960', 'MASVINGO.pdf'),
  ('masvingo-contact-008', (select id from public.branches where upper(name) = 'BHUKA' and upper(country) = 'ZIMBABWE' limit 1), 'BHUKA', 'MASVINGO', 'Treasurer', 'Getrude Sigudu', '0776020794', 'MASVINGO.pdf'),
  ('masvingo-contact-009', (select id from public.branches where upper(name) = 'BHUKA' and upper(country) = 'ZIMBABWE' limit 1), 'BHUKA', 'MASVINGO', 'Secretary', 'Monica Chingoma', '0782080537', 'MASVINGO.pdf'),
  ('masvingo-contact-010', (select id from public.branches where upper(name) = 'STEVEN' and upper(country) = 'ZIMBABWE' limit 1), 'STEVEN', 'MASVINGO', 'Treasurer', 'Pauline Makazhu', '0775529061', 'MASVINGO.pdf'),
  ('masvingo-contact-011', (select id from public.branches where upper(name) = 'STEVEN' and upper(country) = 'ZIMBABWE' limit 1), 'STEVEN', 'MASVINGO', 'Secretary', 'Lucia Chamahwinya', '0774550375', 'MASVINGO.pdf'),
  ('masvingo-contact-012', (select id from public.branches where upper(name) = 'SESE' and upper(country) = 'ZIMBABWE' limit 1), 'SESE', 'MASVINGO', 'Treasurer', 'Ambusai Munemo', '0782976200', 'MASVINGO.pdf'),
  ('masvingo-contact-013', (select id from public.branches where upper(name) = 'SESE' and upper(country) = 'ZIMBABWE' limit 1), 'SESE', 'MASVINGO', 'Secretary', 'Gladys Mapanzure', '0774994889', 'MASVINGO.pdf'),
  ('masvingo-contact-014', (select id from public.branches where upper(name) = 'RHODENE' and upper(country) = 'ZIMBABWE' limit 1), 'RHODENE', 'MASVINGO', 'Treasurer', 'Enester Tsaurai', '0715825144', 'MASVINGO.pdf'),
  ('masvingo-contact-015', (select id from public.branches where upper(name) = 'MASHAVA A' and upper(country) = 'ZIMBABWE' limit 1), 'MASHAVA A', 'MASVINGO', 'Treasurer', 'Edith Muzila', '0775179223', 'MASVINGO.pdf'),
  ('masvingo-contact-016', (select id from public.branches where upper(name) = 'MASHAVA A' and upper(country) = 'ZIMBABWE' limit 1), 'MASHAVA A', 'MASVINGO', 'Secretary', 'Moreblessing Mariga', '0775340221', 'MASVINGO.pdf'),
  ('masvingo-contact-017', (select id from public.branches where upper(name) = 'ZIMUTO' and upper(country) = 'ZIMBABWE' limit 1), 'ZIMUTO', 'MASVINGO', 'Treasurer', 'Comment Magara', '0783485312', 'MASVINGO.pdf'),
  ('masvingo-contact-018', (select id from public.branches where upper(name) = 'ZIMUTO' and upper(country) = 'ZIMBABWE' limit 1), 'ZIMUTO', 'MASVINGO', 'Secretary', 'Rumbidzai Zireva', '0775862015', 'MASVINGO.pdf'),
  ('masvingo-contact-019', (select id from public.branches where upper(name) = 'NEMAMWA' and upper(country) = 'ZIMBABWE' limit 1), 'NEMAMWA', 'MASVINGO', 'Treasurer', 'Fungai Masarira', '0772678984', 'MASVINGO.pdf'),
  ('masvingo-contact-020', (select id from public.branches where upper(name) = 'MASHAVA B' and upper(country) = 'ZIMBABWE' limit 1), 'MASHAVA B', 'MASVINGO', 'Treasurer', 'Joyce Mapurazi', '0778434166', 'MASVINGO.pdf'),
  ('masvingo-contact-021', (select id from public.branches where upper(name) = 'MASHAVA B' and upper(country) = 'ZIMBABWE' limit 1), 'MASHAVA B', 'MASVINGO', 'Secretary', 'Petronella Muyambo', '0783051554', 'MASVINGO.pdf'),
  ('masvingo-contact-022', (select id from public.branches where upper(name) = 'CHARUMBIRA' and upper(country) = 'ZIMBABWE' limit 1), 'CHARUMBIRA', 'MASVINGO', 'Secretary', 'ZAKA', '', 'MASVINGO.pdf'),
  ('masvingo-contact-023', (select id from public.branches where upper(name) = 'DETOYI' and upper(country) = 'ZIMBABWE' limit 1), 'DETOYI', 'MASVINGO', 'Treasurer', 'Knowledge Shoko', '0779439372', 'MASVINGO.pdf'),
  ('masvingo-contact-024', (select id from public.branches where upper(name) = 'DETOYI' and upper(country) = 'ZIMBABWE' limit 1), 'DETOYI', 'MASVINGO', 'Secretary', 'Alice Mutuza', '0780757455', 'MASVINGO.pdf'),
  ('masvingo-contact-025', (select id from public.branches where upper(name) = 'MAWERE' and upper(country) = 'ZIMBABWE' limit 1), 'MAWERE', 'MASVINGO', 'Secretary', '', '0785345656', 'MASVINGO.pdf'),
  ('masvingo-contact-026', (select id from public.branches where upper(name) = 'JERERA A' and upper(country) = 'ZIMBABWE' limit 1), 'JERERA A', 'MASVINGO', 'Treasurer', 'Varaidzo Ziyambi', '0775365287', 'MASVINGO.pdf'),
  ('masvingo-contact-027', (select id from public.branches where upper(name) = 'JERERA A' and upper(country) = 'ZIMBABWE' limit 1), 'JERERA A', 'MASVINGO', 'Secretary', 'Apollonia Khumalo', '0773249725', 'MASVINGO.pdf'),
  ('masvingo-contact-028', (select id from public.branches where upper(name) = 'CHIPFUTI' and upper(country) = 'ZIMBABWE' limit 1), 'CHIPFUTI', 'MASVINGO', 'Treasurer', 'Evelyn Tavengana', '0779314753', 'MASVINGO.pdf'),
  ('masvingo-contact-029', (select id from public.branches where upper(name) = 'CHIPFUTI' and upper(country) = 'ZIMBABWE' limit 1), 'CHIPFUTI', 'MASVINGO', 'Secretary', '', '0784357380', 'MASVINGO.pdf'),
  ('masvingo-contact-030', (select id from public.branches where upper(name) = 'NEMATAVANDA' and upper(country) = 'ZIMBABWE' limit 1), 'NEMATAVANDA', 'MASVINGO', 'Treasurer', 'Flora Vunganai', '0774055139', 'MASVINGO.pdf'),
  ('masvingo-contact-031', (select id from public.branches where upper(name) = 'NEMATAVANDA' and upper(country) = 'ZIMBABWE' limit 1), 'NEMATAVANDA', 'MASVINGO', 'Secretary', 'Jesitha Shazhu', '0784370966', 'MASVINGO.pdf'),
  ('masvingo-contact-032', (select id from public.branches where upper(name) = '4 MILES' and upper(country) = 'ZIMBABWE' limit 1), '4 MILES', 'MASVINGO', 'Treasurer', 'Anatonia Mahoya', '0775592379', 'MASVINGO.pdf'),
  ('masvingo-contact-033', (select id from public.branches where upper(name) = '4 MILES' and upper(country) = 'ZIMBABWE' limit 1), '4 MILES', 'MASVINGO', 'Secretary', 'Mercy Gumede', '0778099527', 'MASVINGO.pdf'),
  ('masvingo-contact-034', (select id from public.branches where upper(name) = 'JERERA B' and upper(country) = 'ZIMBABWE' limit 1), 'JERERA B', 'MASVINGO', 'Treasurer', 'Lucia Mweneziko', '0777390086', 'MASVINGO.pdf'),
  ('masvingo-contact-035', (select id from public.branches where upper(name) = 'JERERA B' and upper(country) = 'ZIMBABWE' limit 1), 'JERERA B', 'MASVINGO', 'Secretary', 'Junica Mahlekete', '0784646357', 'MASVINGO.pdf'),
  ('masvingo-contact-036', (select id from public.branches where upper(name) = 'NDANGA' and upper(country) = 'ZIMBABWE' limit 1), 'NDANGA', 'MASVINGO', 'Treasurer', 'Vimbai Muregi', '0782275729', 'MASVINGO.pdf'),
  ('masvingo-contact-037', (select id from public.branches where upper(name) = 'NDANGA' and upper(country) = 'ZIMBABWE' limit 1), 'NDANGA', 'MASVINGO', 'Secretary', 'Lucia Netsai', '', 'MASVINGO.pdf'),
  ('masvingo-contact-038', (select id from public.branches where upper(name) = 'CHINORUMBA' and upper(country) = 'ZIMBABWE' limit 1), 'CHINORUMBA', 'MASVINGO', 'Treasurer', 'Abigail Muparuri', '0775491213', 'MASVINGO.pdf'),
  ('masvingo-contact-039', (select id from public.branches where upper(name) = 'CHINORUMBA' and upper(country) = 'ZIMBABWE' limit 1), 'CHINORUMBA', 'MASVINGO', 'Secretary', 'Fadzai Chiridza -- 1 of 5 -- Cell No: 0776 889 239/0772 578 586 Email:drandbymakururu@gmail.com Johane The Fifth of Africa International Church Office of the Archbishop Plot No. 24, Mvuma Chinamato Chinokomborera Rudzi Rwemunhu Mutema WemuAfrica', '0771228829', 'MASVINGO.pdf'),
  ('masvingo-contact-040', (select id from public.branches where upper(name) = 'CHIVAMBA' and upper(country) = 'ZIMBABWE' limit 1), 'CHIVAMBA', 'MASVINGO', 'Treasurer', 'Getrude Murinye', '0777533955', 'MASVINGO.pdf'),
  ('masvingo-contact-041', (select id from public.branches where upper(name) = 'CHIVAMBA' and upper(country) = 'ZIMBABWE' limit 1), 'CHIVAMBA', 'MASVINGO', 'Secretary', 'Monica Chitende', '0782053971', 'MASVINGO.pdf'),
  ('masvingo-contact-042', (select id from public.branches where upper(name) = 'MUSARAVA' and upper(country) = 'ZIMBABWE' limit 1), 'MUSARAVA', 'MASVINGO', 'Treasurer', 'Elizabeth Chesa', '0780727760', 'MASVINGO.pdf'),
  ('masvingo-contact-043', (select id from public.branches where upper(name) = 'GUMBO' and upper(country) = 'ZIMBABWE' limit 1), 'GUMBO', 'MASVINGO', 'Treasurer', 'Emma Chiwomo', '0785058652', 'MASVINGO.pdf'),
  ('masvingo-contact-044', (select id from public.branches where upper(name) = 'GUMBO' and upper(country) = 'ZIMBABWE' limit 1), 'GUMBO', 'MASVINGO', 'Secretary', '', '0777381315', 'MASVINGO.pdf'),
  ('masvingo-contact-045', (select id from public.branches where upper(name) = 'VEZA' and upper(country) = 'ZIMBABWE' limit 1), 'VEZA', 'MASVINGO', 'Secretary', 'MBERENGWA', '', 'MASVINGO.pdf'),
  ('masvingo-contact-046', (select id from public.branches where upper(name) = 'SKUTA' and upper(country) = 'ZIMBABWE' limit 1), 'SKUTA', 'MASVINGO', 'Treasurer', 'Sithembiso Sibanda', '0787307959', 'MASVINGO.pdf'),
  ('masvingo-contact-047', (select id from public.branches where upper(name) = 'SKUTA' and upper(country) = 'ZIMBABWE' limit 1), 'SKUTA', 'MASVINGO', 'Secretary', 'Farai Masuku', '0782712425', 'MASVINGO.pdf'),
  ('masvingo-contact-048', (select id from public.branches where upper(name) = 'FILABUSI' and upper(country) = 'ZIMBABWE' limit 1), 'FILABUSI', 'MASVINGO', 'Treasurer', 'Sakhile Sibanda', '0785601045', 'MASVINGO.pdf'),
  ('masvingo-contact-049', (select id from public.branches where upper(name) = 'FILABUSI' and upper(country) = 'ZIMBABWE' limit 1), 'FILABUSI', 'MASVINGO', 'Secretary', 'Sikholiwe Dlamini', '0716231363', 'MASVINGO.pdf'),
  ('masvingo-contact-050', (select id from public.branches where upper(name) = 'YORKO' and upper(country) = 'ZIMBABWE' limit 1), 'YORKO', 'MASVINGO', 'Treasurer', 'Ruregerero Zhou', '0714090290', 'MASVINGO.pdf'),
  ('masvingo-contact-051', (select id from public.branches where upper(name) = 'YORKO' and upper(country) = 'ZIMBABWE' limit 1), 'YORKO', 'MASVINGO', 'Secretary', 'Margret Chidharara', '0787083083', 'MASVINGO.pdf'),
  ('masvingo-contact-052', (select id from public.branches where upper(name) = 'MBERENGWA OFFICE' and upper(country) = 'ZIMBABWE' limit 1), 'MBERENGWA OFFICE', 'MASVINGO', 'Treasurer', 'Beauty Ranganai', '0785608079', 'MASVINGO.pdf'),
  ('masvingo-contact-053', (select id from public.branches where upper(name) = 'MBERENGWA OFFICE' and upper(country) = 'ZIMBABWE' limit 1), 'MBERENGWA OFFICE', 'MASVINGO', 'Secretary', 'Theresa Timitiyo', '0771381831', 'MASVINGO.pdf'),
  ('masvingo-contact-054', (select id from public.branches where upper(name) = 'NKANKEZI' and upper(country) = 'ZIMBABWE' limit 1), 'NKANKEZI', 'MASVINGO', 'Treasurer', 'Sazizo Mangena', '0711823282', 'MASVINGO.pdf'),
  ('masvingo-contact-055', (select id from public.branches where upper(name) = 'NKANKEZI' and upper(country) = 'ZIMBABWE' limit 1), 'NKANKEZI', 'MASVINGO', 'Secretary', 'Patisiwe Dube', '0771157852', 'MASVINGO.pdf'),
  ('masvingo-contact-056', (select id from public.branches where upper(name) = 'VANGUARD' and upper(country) = 'ZIMBABWE' limit 1), 'VANGUARD', 'MASVINGO', 'Treasurer', 'Sekai Moyo', '0716448239', 'MASVINGO.pdf'),
  ('masvingo-contact-057', (select id from public.branches where upper(name) = 'VANGUARD' and upper(country) = 'ZIMBABWE' limit 1), 'VANGUARD', 'MASVINGO', 'Secretary', 'Lawrencia Mhofu', '0783089202', 'MASVINGO.pdf'),
  ('masvingo-contact-058', (select id from public.branches where upper(name) = 'BVUTE' and upper(country) = 'ZIMBABWE' limit 1), 'BVUTE', 'MASVINGO', 'Treasurer', 'Persistance Zhou', '0717119807', 'MASVINGO.pdf'),
  ('masvingo-contact-059', (select id from public.branches where upper(name) = 'NETAR' and upper(country) = 'ZIMBABWE' limit 1), 'NETAR', 'MASVINGO', 'Treasurer', 'Patricia Zhou', '0713483788', 'MASVINGO.pdf'),
  ('masvingo-contact-060', (select id from public.branches where upper(name) = 'MBALABALA' and upper(country) = 'ZIMBABWE' limit 1), 'MBALABALA', 'MASVINGO', 'Secretary', 'Ainess Phiri', '0787308589', 'MASVINGO.pdf'),
  ('masvingo-contact-061', (select id from public.branches where upper(name) = 'BMINE' and upper(country) = 'ZIMBABWE' limit 1), 'BMINE', 'MASVINGO', 'Treasurer', 'Brian Moyo', '0710411728', 'MASVINGO.pdf'),
  ('masvingo-contact-062', (select id from public.branches where upper(name) = 'BMINE' and upper(country) = 'ZIMBABWE' limit 1), 'BMINE', 'MASVINGO', 'Secretary', 'Salakhupe Bvute', '0782900134', 'MASVINGO.pdf'),
  ('masvingo-contact-063', (select id from public.branches where upper(name) = 'PHONEX' and upper(country) = 'ZIMBABWE' limit 1), 'PHONEX', 'MASVINGO', 'Secretary', 'GUTU', '', 'MASVINGO.pdf'),
  ('masvingo-contact-064', (select id from public.branches where upper(name) = 'MAUNGWA' and upper(country) = 'ZIMBABWE' limit 1), 'MAUNGWA', 'MASVINGO', 'Treasurer', 'Stella Dunira', '0777598904', 'MASVINGO.pdf'),
  ('masvingo-contact-065', (select id from public.branches where upper(name) = 'MAUNGWA' and upper(country) = 'ZIMBABWE' limit 1), 'MAUNGWA', 'MASVINGO', 'Secretary', 'Rudo Jiriengwa', '0771746725', 'MASVINGO.pdf'),
  ('masvingo-contact-066', (select id from public.branches where upper(name) = 'CHATSWORTHS' and upper(country) = 'ZIMBABWE' limit 1), 'CHATSWORTHS', 'MASVINGO', 'Treasurer', 'Kundai Chidagwa', '0778922108', 'MASVINGO.pdf'),
  ('masvingo-contact-067', (select id from public.branches where upper(name) = 'CHATSWORTHS' and upper(country) = 'ZIMBABWE' limit 1), 'CHATSWORTHS', 'MASVINGO', 'Secretary', 'Tatenda Mukwinya', '0775511710', 'MASVINGO.pdf'),
  ('masvingo-contact-068', (select id from public.branches where upper(name) = 'GUTU CENTER' and upper(country) = 'ZIMBABWE' limit 1), 'GUTU CENTER', 'MASVINGO', 'Treasurer', 'Lucia Mahofa', '0774387509', 'MASVINGO.pdf'),
  ('masvingo-contact-069', (select id from public.branches where upper(name) = 'GUTU CENTER' and upper(country) = 'ZIMBABWE' limit 1), 'GUTU CENTER', 'MASVINGO', 'Secretary', 'Beatrice Machingambi', '0773908230', 'MASVINGO.pdf'),
  ('masvingo-contact-070', (select id from public.branches where upper(name) = 'MUCHECHETE' and upper(country) = 'ZIMBABWE' limit 1), 'MUCHECHETE', 'MASVINGO', 'Treasurer', 'Idah Chirovaamai', '0775753092', 'MASVINGO.pdf'),
  ('masvingo-contact-071', (select id from public.branches where upper(name) = 'MUCHECHETE' and upper(country) = 'ZIMBABWE' limit 1), 'MUCHECHETE', 'MASVINGO', 'Secretary', 'Loveness Mapfumo', '0781536513', 'MASVINGO.pdf'),
  ('masvingo-contact-072', (select id from public.branches where upper(name) = 'ZVAVAHERA' and upper(country) = 'ZIMBABWE' limit 1), 'ZVAVAHERA', 'MASVINGO', 'Treasurer', 'Constance Mubwanda', '0773533986', 'MASVINGO.pdf'),
  ('masvingo-contact-073', (select id from public.branches where upper(name) = 'ZVAVAHERA' and upper(country) = 'ZIMBABWE' limit 1), 'ZVAVAHERA', 'MASVINGO', 'Secretary', 'Monica Mutukwa', '', 'MASVINGO.pdf'),
  ('masvingo-contact-074', (select id from public.branches where upper(name) = 'MUSHAYAVANHU' and upper(country) = 'ZIMBABWE' limit 1), 'MUSHAYAVANHU', 'MASVINGO', 'Treasurer', 'Emmha Vengesai', '0781441607', 'MASVINGO.pdf'),
  ('masvingo-contact-075', (select id from public.branches where upper(name) = 'GONYE' and upper(country) = 'ZIMBABWE' limit 1), 'GONYE', 'MASVINGO', 'Treasurer', 'Sarah Kuveya', '0771020250', 'MASVINGO.pdf'),
  ('masvingo-contact-076', (select id from public.branches where upper(name) = 'GONYE' and upper(country) = 'ZIMBABWE' limit 1), 'GONYE', 'MASVINGO', 'Secretary', 'Marian Manjeya', '0785134058', 'MASVINGO.pdf'),
  ('masvingo-contact-077', (select id from public.branches where upper(name) = 'HUNDUZA' and upper(country) = 'ZIMBABWE' limit 1), 'HUNDUZA', 'MASVINGO', 'Treasurer', 'Sharon Hunduza -- 2 of 5 -- Cell No: 0776 889 239/0772 578 586 Email:drandbymakururu@gmail.com Johane The Fifth of Africa International Church Office of the Archbishop Plot No. 24, Mvuma Chinamato Chinokomborera Rudzi Rwemunhu Mutema WemuAfrica', '0784942682', 'MASVINGO.pdf'),
  ('masvingo-contact-078', (select id from public.branches where upper(name) = 'BHASERA' and upper(country) = 'ZIMBABWE' limit 1), 'BHASERA', 'MASVINGO', 'Treasurer', 'Angeline Bere', '0786881496', 'MASVINGO.pdf'),
  ('masvingo-contact-079', (select id from public.branches where upper(name) = 'BHASERA' and upper(country) = 'ZIMBABWE' limit 1), 'BHASERA', 'MASVINGO', 'Secretary', 'Slyvia Masuku', '0784983213', 'MASVINGO.pdf'),
  ('masvingo-contact-080', (select id from public.branches where upper(name) = 'TACHI' and upper(country) = 'ZIMBABWE' limit 1), 'TACHI', 'MASVINGO', 'Treasurer', 'Tariro Rukovo', '0784418557', 'MASVINGO.pdf'),
  ('masvingo-contact-081', (select id from public.branches where upper(name) = 'TACHI' and upper(country) = 'ZIMBABWE' limit 1), 'TACHI', 'MASVINGO', 'Secretary', 'Chiedza Humanikwe', '0777813450', 'MASVINGO.pdf'),
  ('masvingo-contact-082', (select id from public.branches where upper(name) = 'NERUPIRI' and upper(country) = 'ZIMBABWE' limit 1), 'NERUPIRI', 'MASVINGO', 'Treasurer', 'Felistas Matongo', '0773935839', 'MASVINGO.pdf'),
  ('masvingo-contact-083', (select id from public.branches where upper(name) = 'NERUPIRI' and upper(country) = 'ZIMBABWE' limit 1), 'NERUPIRI', 'MASVINGO', 'Secretary', 'Sondekhile Mpofu', '0777777069', 'MASVINGO.pdf'),
  ('masvingo-contact-084', (select id from public.branches where upper(name) = 'CHAGWIZA' and upper(country) = 'ZIMBABWE' limit 1), 'CHAGWIZA', 'MASVINGO', 'Treasurer', 'Patience Gwaza', '0779342099', 'MASVINGO.pdf'),
  ('masvingo-contact-085', (select id from public.branches where upper(name) = 'CHAGWIZA' and upper(country) = 'ZIMBABWE' limit 1), 'CHAGWIZA', 'MASVINGO', 'Secretary', 'Tendai Mutero', '0784685407', 'MASVINGO.pdf'),
  ('masvingo-contact-086', (select id from public.branches where upper(name) = 'MUGONI' and upper(country) = 'ZIMBABWE' limit 1), 'MUGONI', 'MASVINGO', 'Secretary', 'Clarieta Ruhinga', '0771353739', 'MASVINGO.pdf'),
  ('masvingo-contact-087', (select id from public.branches where upper(name) = 'MATIZHA' and upper(country) = 'ZIMBABWE' limit 1), 'MATIZHA', 'MASVINGO', 'Treasurer', 'Anna Svondo', '', 'MASVINGO.pdf'),
  ('masvingo-contact-088', (select id from public.branches where upper(name) = 'MATIZHA' and upper(country) = 'ZIMBABWE' limit 1), 'MATIZHA', 'MASVINGO', 'Secretary', 'Faith Ndawi MWENEZI', '0778331204', 'MASVINGO.pdf'),
  ('masvingo-contact-089', (select id from public.branches where upper(name) = 'NGUNDU' and upper(country) = 'ZIMBABWE' limit 1), 'NGUNDU', 'MASVINGO', 'Treasurer', 'Margret Takayambirwa', '0774137930', 'MASVINGO.pdf'),
  ('masvingo-contact-090', (select id from public.branches where upper(name) = 'RUTENGA' and upper(country) = 'ZIMBABWE' limit 1), 'RUTENGA', 'MASVINGO', 'Treasurer', 'Tsitsi Dziva', '0784983317', 'MASVINGO.pdf'),
  ('masvingo-contact-091', (select id from public.branches where upper(name) = 'RUTENGA' and upper(country) = 'ZIMBABWE' limit 1), 'RUTENGA', 'MASVINGO', 'Secretary', 'Eunice Ndlovu', '0783344647', 'MASVINGO.pdf'),
  ('masvingo-contact-092', (select id from public.branches where upper(name) = 'LUNDI' and upper(country) = 'ZIMBABWE' limit 1), 'LUNDI', 'MASVINGO', 'Treasurer', 'Grace Makanyanga', '0771624341', 'MASVINGO.pdf'),
  ('masvingo-contact-093', (select id from public.branches where upper(name) = 'LUNDI' and upper(country) = 'ZIMBABWE' limit 1), 'LUNDI', 'MASVINGO', 'Secretary', 'Jennifer Kawero', '0771136626', 'MASVINGO.pdf'),
  ('masvingo-contact-094', (select id from public.branches where upper(name) = 'MARANDA TURN' and upper(country) = 'ZIMBABWE' limit 1), 'MARANDA TURN', 'MASVINGO', 'Treasurer', 'Muchanyara Gara', '0774485443', 'MASVINGO.pdf'),
  ('masvingo-contact-095', (select id from public.branches where upper(name) = 'ZIVUKU' and upper(country) = 'ZIMBABWE' limit 1), 'ZIVUKU', 'MASVINGO', 'Treasurer', 'Sheillah Ganyani', '0771858314', 'MASVINGO.pdf'),
  ('masvingo-contact-096', (select id from public.branches where upper(name) = 'SHONGAMITI' and upper(country) = 'ZIMBABWE' limit 1), 'SHONGAMITI', 'MASVINGO', 'Treasurer', 'Varaidzo Magwaro', '0779027468', 'MASVINGO.pdf'),
  ('masvingo-contact-097', (select id from public.branches where upper(name) = 'SHONGAMITI' and upper(country) = 'ZIMBABWE' limit 1), 'SHONGAMITI', 'MASVINGO', 'Secretary', 'Tinayeishe Musasiwa', '0788362996', 'MASVINGO.pdf'),
  ('masvingo-contact-098', (select id from public.branches where upper(name) = 'RENCO MINE' and upper(country) = 'ZIMBABWE' limit 1), 'RENCO MINE', 'MASVINGO', 'Treasurer', 'Grace Chidanhika', '0773903417/0716404931', 'MASVINGO.pdf'),
  ('masvingo-contact-099', (select id from public.branches where upper(name) = 'RUPIKE' and upper(country) = 'ZIMBABWE' limit 1), 'RUPIKE', 'MASVINGO', 'Treasurer', 'Monica Nezvikonde', '0787484265', 'MASVINGO.pdf'),
  ('masvingo-contact-100', (select id from public.branches where upper(name) = 'GORORO' and upper(country) = 'ZIMBABWE' limit 1), 'GORORO', 'MASVINGO', 'Treasurer', 'Enita Hutete', '0779913060', 'MASVINGO.pdf'),
  ('masvingo-contact-101', (select id from public.branches where upper(name) = 'GORORO' and upper(country) = 'ZIMBABWE' limit 1), 'GORORO', 'MASVINGO', 'Secretary', 'Fungai Duve', '0779547924', 'MASVINGO.pdf'),
  ('masvingo-contact-102', (select id from public.branches where upper(name) = 'MUSEBA' and upper(country) = 'ZIMBABWE' limit 1), 'MUSEBA', 'MASVINGO', 'Treasurer', 'Erita Chibike', '0786155209', 'MASVINGO.pdf'),
  ('masvingo-contact-103', (select id from public.branches where upper(name) = 'NESHURO' and upper(country) = 'ZIMBABWE' limit 1), 'NESHURO', 'MASVINGO', 'Treasurer', 'Patience Murombo', '0784874485', 'MASVINGO.pdf'),
  ('masvingo-contact-104', (select id from public.branches where upper(name) = 'ZVISHAVANE CHIGOMBA' and upper(country) = 'ZIMBABWE' limit 1), 'ZVISHAVANE CHIGOMBA', 'MASVINGO', 'Treasurer', 'Respect Magaya', '0783554820', 'MASVINGO.pdf'),
  ('masvingo-contact-105', (select id from public.branches where upper(name) = 'ZVISHAVANE CHIGOMBA' and upper(country) = 'ZIMBABWE' limit 1), 'ZVISHAVANE CHIGOMBA', 'MASVINGO', 'Secretary', '-- 3 of 5 -- Cell No: Email:drandbymakururu@gmail.com Johane The Fifth of Africa International Church Office of the Archbishop Plot No. 24, Mvuma Chinamato Chinokomborera Rudzi Rwemunhu Mutema WemuAfrica', '0776889239/0772578586', 'MASVINGO.pdf'),
  ('masvingo-contact-106', (select id from public.branches where upper(name) = '4 MILES' and upper(country) = 'ZIMBABWE' limit 1), '4 MILES', 'MASVINGO', 'Treasurer', 'Liviniah Dube', '0774478628/0715057556', 'MASVINGO.pdf'),
  ('masvingo-contact-107', (select id from public.branches where upper(name) = 'VUGWI' and upper(country) = 'ZIMBABWE' limit 1), 'VUGWI', 'MASVINGO', 'Treasurer', 'Nokhutula Mbizo', '0719758247/0774577334', 'MASVINGO.pdf'),
  ('masvingo-contact-108', (select id from public.branches where upper(name) = 'SIBOZA' and upper(country) = 'ZIMBABWE' limit 1), 'SIBOZA', 'MASVINGO', 'Secretary', 'Tinovimba Nyoni', '0781096485', 'MASVINGO.pdf'),
  ('masvingo-contact-109', (select id from public.branches where upper(name) = 'CHITOWA' and upper(country) = 'ZIMBABWE' limit 1), 'CHITOWA', 'MASVINGO', 'Treasurer', 'Marian Mandava', '0781269406', 'MASVINGO.pdf'),
  ('masvingo-contact-110', (select id from public.branches where upper(name) = 'CHITOWA' and upper(country) = 'ZIMBABWE' limit 1), 'CHITOWA', 'MASVINGO', 'Secretary', 'Sorofina Machowa', '0775642811', 'MASVINGO.pdf'),
  ('masvingo-contact-111', (select id from public.branches where upper(name) = 'MAGLASS' and upper(country) = 'ZIMBABWE' limit 1), 'MAGLASS', 'MASVINGO', 'Secretary', 'CHIREDZI', '', 'MASVINGO.pdf'),
  ('masvingo-contact-112', (select id from public.branches where upper(name) = 'CHIREDZI LYONAIS' and upper(country) = 'ZIMBABWE' limit 1), 'CHIREDZI LYONAIS', 'MASVINGO', 'Treasurer', 'Shyleen Mayoyo', '0773286325', 'MASVINGO.pdf'),
  ('masvingo-contact-113', (select id from public.branches where upper(name) = 'TRIANGLE A' and upper(country) = 'ZIMBABWE' limit 1), 'TRIANGLE A', 'MASVINGO', 'Treasurer', 'Tsungai Mwenezi', '0788325247', 'MASVINGO.pdf'),
  ('masvingo-contact-114', (select id from public.branches where upper(name) = 'MKWASINE B' and upper(country) = 'ZIMBABWE' limit 1), 'MKWASINE B', 'MASVINGO', 'Treasurer', 'Moleen Vandirayi', '0775997890', 'MASVINGO.pdf'),
  ('masvingo-contact-115', (select id from public.branches where upper(name) = 'SAMBA RANCH' and upper(country) = 'ZIMBABWE' limit 1), 'SAMBA RANCH', 'MASVINGO', 'Treasurer', 'Chrispen Njaravani', '0776717667', 'MASVINGO.pdf'),
  ('masvingo-contact-116', (select id from public.branches where upper(name) = 'MASHOKO' and upper(country) = 'ZIMBABWE' limit 1), 'MASHOKO', 'MASVINGO', 'Treasurer', 'Emma Tivakaise', '0779904623', 'MASVINGO.pdf'),
  ('masvingo-contact-117', (select id from public.branches where upper(name) = 'RENCO TURN' and upper(country) = 'ZIMBABWE' limit 1), 'RENCO TURN', 'MASVINGO', 'Treasurer', 'Naome Nhotito', '0780955807', 'MASVINGO.pdf'),
  ('masvingo-contact-118', (select id from public.branches where upper(name) = 'GUTSARUZHINJI' and upper(country) = 'ZIMBABWE' limit 1), 'GUTSARUZHINJI', 'MASVINGO', 'Secretary', 'Shylet Tenga', '0783317903', 'MASVINGO.pdf'),
  ('masvingo-contact-119', (select id from public.branches where upper(name) = 'VHENEKA A' and upper(country) = 'ZIMBABWE' limit 1), 'VHENEKA A', 'MASVINGO', 'Secretary', 'BIKITA', '', 'MASVINGO.pdf'),
  ('masvingo-contact-120', (select id from public.branches where upper(name) = 'NYIKA' and upper(country) = 'ZIMBABWE' limit 1), 'NYIKA', 'MASVINGO', 'Treasurer', 'Rumbidzai Mandikiyana', '0781443219', 'MASVINGO.pdf'),
  ('masvingo-contact-121', (select id from public.branches where upper(name) = 'MUPAMAONDE' and upper(country) = 'ZIMBABWE' limit 1), 'MUPAMAONDE', 'MASVINGO', 'Treasurer', 'Evis P Hove', '0780112709', 'MASVINGO.pdf'),
  ('masvingo-contact-122', (select id from public.branches where upper(name) = 'SILVEIRA' and upper(country) = 'ZIMBABWE' limit 1), 'SILVEIRA', 'MASVINGO', 'Treasurer', 'Vesta Shavane', '0784898146', 'MASVINGO.pdf'),
  ('masvingo-contact-123', (select id from public.branches where upper(name) = 'PAMUSHANA' and upper(country) = 'ZIMBABWE' limit 1), 'PAMUSHANA', 'MASVINGO', 'Treasurer', 'Ebeleena Sosera', '0774781293', 'MASVINGO.pdf'),
  ('masvingo-contact-124', (select id from public.branches where upper(name) = 'MAKUVAZA' and upper(country) = 'ZIMBABWE' limit 1), 'MAKUVAZA', 'MASVINGO', 'Treasurer', 'Stella Mavumashava', '0774796956', 'MASVINGO.pdf'),
  ('masvingo-contact-125', (select id from public.branches where upper(name) = 'JENETI' and upper(country) = 'ZIMBABWE' limit 1), 'JENETI', 'MASVINGO', 'Treasurer', 'Josephine Makotore', '07792316180', 'MASVINGO.pdf'),
  ('masvingo-contact-126', (select id from public.branches where upper(name) = 'CHIREMWAREMWA' and upper(country) = 'ZIMBABWE' limit 1), 'CHIREMWAREMWA', 'MASVINGO', 'Treasurer', 'Evelyn Nehwasvi -- 4 of 5 -- Cell No: 0776 889 239/0772 578 586 Email:drandbymakururu@gmail.com Johane The Fifth of Africa International Church Office of the Archbishop Plot No. 24, Mvuma Chinamato Chinokomborera Rudzi Rwemunhu Mutema WemuAfrica', '0779477074', 'MASVINGO.pdf'),
  ('masvingo-contact-127', (select id from public.branches where upper(name) = 'NJARAVANI' and upper(country) = 'ZIMBABWE' limit 1), 'NJARAVANI', 'MASVINGO', 'Treasurer', 'Cornillia Murinye', '0774808273', 'MASVINGO.pdf'),
  ('masvingo-contact-128', (select id from public.branches where upper(name) = 'PADARE' and upper(country) = 'ZIMBABWE' limit 1), 'PADARE', 'MASVINGO', 'Treasurer', 'Diniwe Lunga', '0773016499', 'MASVINGO.pdf'),
  ('masvingo-contact-129', (select id from public.branches where upper(name) = 'PADARE' and upper(country) = 'ZIMBABWE' limit 1), 'PADARE', 'MASVINGO', 'Secretary', 'CHIVI', '', 'MASVINGO.pdf'),
  ('masvingo-contact-130', (select id from public.branches where upper(name) = 'CHIVI CENTER' and upper(country) = 'ZIMBABWE' limit 1), 'CHIVI CENTER', 'MASVINGO', 'Treasurer', 'Grace', '0776374722', 'MASVINGO.pdf'),
  ('masvingo-contact-131', (select id from public.branches where upper(name) = 'CHIBI TURN' and upper(country) = 'ZIMBABWE' limit 1), 'CHIBI TURN', 'MASVINGO', 'Treasurer', 'Martha Mugweni', '0773311699', 'MASVINGO.pdf'),
  ('masvingo-contact-132', (select id from public.branches where upper(name) = 'DAVIRA' and upper(country) = 'ZIMBABWE' limit 1), 'DAVIRA', 'MASVINGO', 'Secretary', '-- 5 of 5 --', '', 'MASVINGO.pdf')
on conflict (id) do update set
  branch_id = excluded.branch_id,
  branch_name = excluded.branch_name,
  province = excluded.province,
  role = excluded.role,
  name = excluded.name,
  phone = excluded.phone,
  source = excluded.source;
