-- Imported from Matebeleland_North.pdf.
-- Unclear names, phone numbers, and amounts are preserved as marked or blank.
-- Crossed-out phone entries are intentionally blank.
-- Uses the shared protected Burial Society registry table.

insert into public.burial_society_member_registry
  (id, source_number, full_name, phone, amount_paid, linked, linked_member_id, linked_auth_user_id, source)
values
  ('matabeleland-north-burial-001', 1, 'R… Ndlovu', '0713129494', '10.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-002', 2, 'Brenda Mavuma', '', '10.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-003', 3, 'Andrew Chombo', '0716632561', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-004', 4, 'Gladys Moyo', '0715905862', '12.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-005', 5, 'Tonderai Mupera', '0782594868', '12.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-006', 6, 'Peter Muchando', '0784882385', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-007', 7, 'Tonderai Sibanda', '0715514329', '16.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-008', 8, 'Gertrude Sibanda', '', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-009', 9, 'Siphephelangani Ncube', '', '12.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-010', 10, 'Mavis Bhebhe', '', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-011', 11, 'Fanny Michael Ngarur?', '', '12.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-012', 12, 'Eliza Huna?', '0719530446', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-013', 13, 'Josephine Mavhe', '0713649761', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-014', 14, 'Anna Mrem?anda', '0715375855', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-015', 15, 'Senzeni Sibanda', '0714851386', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-016', 16, 'Solomon Dlomo', '0783789527', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-017', 17, 'Wesley M Gom?nde', '0716923866', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-018', 18, 'Dwak?wel? Ndlh?vu', '0780254545', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-019', 19, 'Elizabeth Lup?ndhla', '0715904047', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-020', 20, 'Nobuhle Gumbo', '0745996446', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-021', 21, 'Jez?nica M?konodwa?', '0782216548', '12.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-022', 22, 'Catherine Muyemba', '0745230421', '16.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-023', 23, 'Thembiso Dube', '0781949238', '12.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-024', 24, 'Paulinah Nyoni', '0782531218', '16.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-025', 25, 'Nkosikh? Sibanda', '', '16.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-026', 26, 'Becky Dube', '0716410238', '16.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-027', 27, 'Nobuhle Ndlovu', '0783348086', '12.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-028', 28, 'Blessing Nyoni', '0719040823', '12.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-029', 29, 'William Muleya', '0715321398', '16.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-030', 30, 'Sibongile Dube', '0784245908', '14.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-031', 31, 'Service Nyoni', '0711133053', '14.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-032', 32, 'Thembinkosi Moyo', '0719555836', '10.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-033', 33, 'Gladys Dube', '0711867315', '12.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-034', 34, 'Bright Ncube', '0715415340', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-035', 35, 'Rident Mwinde', '078540412', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-036', 36, 'Crispen Mathe', '078000491', '8.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-037', 37, 'Agnes Mhl?wan?', '071596168', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-038', 38, 'Sike Ch?ope', '0715140311', '8.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-039', 39, 'Bekani Song?', '', '3.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-040', 40, 'Vincent Dube', '', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-041', 41, 'Schul?kile Moyo', '', '3.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-042', 42, 'Cecilia Ndebele', '', '3.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-043', 43, 'Darlington Cum?remhete', '', '3.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-044', 44, 'Elicia Mbewe', '', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-045', 45, 'Catherine Muyembe', '', '3.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-046', 46, 'Andrew Gaviro', '', '3.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-047', 47, 'Westnica Mudenhwa', '', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-048', 48, 'Bright Ncube', '', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-049', 49, 'Paulinah Nyoni', '', '6.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-050', 50, 'Nobuhle Ndlovu', '', '14.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt'),
  ('matabeleland-north-burial-051', 51, 'Service Nyoni', '', '14.00', false, null, null, 'matabeleland_north_burial_members_extracted.txt')
on conflict (id) do update set
  source_number = excluded.source_number,
  full_name = excluded.full_name,
  phone = excluded.phone,
  amount_paid = excluded.amount_paid,
  source = excluded.source,
  updated_at = now();
