-- Generated from PROPHETS DATA.xls. Review before running in Supabase.
-- Sheets: HARARE, MASVINGO, MIDLANDS, MASHWEST

insert into public.branches
  (id, name, province, country, prophet, phone, address, gps, members, code, status, founded, notes, is_hq)
values
  ('zw-harare-2', 'GEROGE', 'HARARE', 'Zimbabwe', 'TARISAI MAKURUWANI', '0774279072', 'CHADCOMBE District, Zimbabwe', '', '0', 'J5-ZW-HAR-001', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-3', 'SUNNINGDALE', 'HARARE', 'Zimbabwe', 'ZVIKOMBORERO', '0780401147', 'CHADCOMBE District, Zimbabwe', '', '0', 'J5-ZW-HAR-002', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-4', 'MBARE', 'HARARE', 'Zimbabwe', 'LEON', '0789992421', 'CHADCOMBE District, Zimbabwe', '', '0', 'J5-ZW-HAR-003', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-5', 'OVERSPILL', 'HARARE', 'Zimbabwe', 'WITNESS', '0776689644', 'CHADCOMBE District, Zimbabwe', '', '0', 'J5-ZW-HAR-004', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-6', 'LOCAL BOARDS', 'HARARE', 'Zimbabwe', 'EMA', '0774870309', 'CHADCOMBE District, Zimbabwe', '', '0', 'J5-ZW-HAR-005', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-7', 'CORNERSTONE', 'HARARE', 'Zimbabwe', 'SIMBA', '0789002510', 'CHADCOMBE District, Zimbabwe', '', '0', 'J5-ZW-HAR-006', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-8', 'GLENWOOD', 'HARARE', 'Zimbabwe', 'SANDRA', '0711884885', 'CHADCOMBE District, Zimbabwe', '', '0', 'J5-ZW-HAR-007', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-9', 'MABVUKU', 'HARARE', 'Zimbabwe', 'SHYLET', '077647679', 'MABVUKU District, Zimbabwe', '', '0', 'J5-ZW-HAR-008', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-10', 'CHIKURUBHI', 'HARARE', 'Zimbabwe', 'ALLEN TAPERA', '078365105', 'MABVUKU District, Zimbabwe', '', '0', 'J5-ZW-HAR-009', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-11', 'GAZEBO', 'HARARE', 'Zimbabwe', 'MAPHOSA', '0778642666', 'MABVUKU District, Zimbabwe', '', '0', 'J5-ZW-HAR-010', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-12', 'DAMAFALLS', 'HARARE', 'Zimbabwe', 'GETRUDE', '0776289372', 'MABVUKU District, Zimbabwe', '', '0', 'J5-ZW-HAR-011', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-13', 'HATCLIFF', 'HARARE', 'Zimbabwe', 'WASHINGTON', '0786911230', 'MABVUKU District, Zimbabwe', '', '0', 'J5-ZW-HAR-012', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-14', 'CHISHAWASHA', 'HARARE', 'Zimbabwe', 'BRIAN', '0787414752', 'MABVUKU District, Zimbabwe', '', '0', 'J5-ZW-HAR-013', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-15', 'HATCLIFF GAMBELA', 'HARARE', 'Zimbabwe', 'AUDREY', '0781399601', 'MABVUKU District, Zimbabwe', '', '0', 'J5-ZW-HAR-014', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-16', 'HATCLIFF FRENDSHIP', 'HARARE', 'Zimbabwe', 'PAMHIDZAI', '07808637', 'MABVUKU District, Zimbabwe', '', '0', 'J5-ZW-HAR-015', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-17', 'WALKERMUTAMBA', 'HARARE', 'Zimbabwe', 'TENDAI', '0784364134', 'MABVUKU District, Zimbabwe', '', '0', 'J5-ZW-HAR-016', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-18', 'RUWA', 'HARARE', 'Zimbabwe', 'VICTOR', '0783425908', 'RUWA District, Zimbabwe', '', '0', 'J5-ZW-HAR-017', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-19', 'MAJURU', 'HARARE', 'Zimbabwe', 'ABIGIRL', '0777974405', 'RUWA District, Zimbabwe', '', '0', 'J5-ZW-HAR-018', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-20', 'SOLOMIO', 'HARARE', 'Zimbabwe', 'ABEL', '0788343498', 'RUWA District, Zimbabwe', '', '0', 'J5-ZW-HAR-019', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-21', 'ROCKVIEW', 'HARARE', 'Zimbabwe', 'CHESI', '0719009140', 'RUWA District, Zimbabwe', '', '0', 'J5-ZW-HAR-020', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-22', 'BOKA', 'HARARE', 'Zimbabwe', 'DHUDHUZILE', '0780179250', 'BOKA District, Zimbabwe', '', '0', 'J5-ZW-HAR-021', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-23', 'MASTEPS', 'HARARE', 'Zimbabwe', 'CHINA', '0781750684', 'BOKA District, Zimbabwe', '', '0', 'J5-ZW-HAR-022', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-24', 'NYATSIME', 'HARARE', 'Zimbabwe', 'EDWINE', '0780401147', 'BOKA District, Zimbabwe', '', '0', 'J5-ZW-HAR-023', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-25', 'BETREACE', 'HARARE', 'Zimbabwe', 'EGA', '0717765938', 'BOKA District, Zimbabwe', '', '0', 'J5-ZW-HAR-024', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-26', 'GOMBIRO', 'HARARE', 'Zimbabwe', 'TENDAI', '0789921293', 'BOKA District, Zimbabwe', '', '0', 'J5-ZW-HAR-025', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-27', 'NYATSIME B', 'HARARE', 'Zimbabwe', 'PROGRESS', '0778459092', 'BOKA District, Zimbabwe', '', '0', 'J5-ZW-HAR-026', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-28', 'STONERIDGE', 'HARARE', 'Zimbabwe', 'MEMORY DUMBA', '0719830335', 'BOKA District, Zimbabwe', '', '0', 'J5-ZW-HAR-027', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-29', 'ASPINDALE', 'HARARE', 'Zimbabwe', 'REGINA', '0781302167', 'ASPINDALE District, Zimbabwe', '', '0', 'J5-ZW-HAR-028', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-30', 'GLENORA', 'HARARE', 'Zimbabwe', 'KNOWLEDGE', '', 'ASPINDALE District, Zimbabwe', '', '0', 'J5-ZW-HAR-029', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-31', 'KFC', 'HARARE', 'Zimbabwe', 'TANAKA', '0785134184', 'ASPINDALE District, Zimbabwe', '', '0', 'J5-ZW-HAR-030', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-32', 'WHITEHOUSE', 'HARARE', 'Zimbabwe', 'ANNA', '0776702978', 'ASPINDALE District, Zimbabwe', '', '0', 'J5-ZW-HAR-031', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-33', 'CABS', 'HARARE', 'Zimbabwe', 'PATRICK', '0776946732', 'ASPINDALE District, Zimbabwe', '', '0', 'J5-ZW-HAR-032', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-34', 'CHURUFARM', 'HARARE', 'Zimbabwe', 'SARUDZAI', '0774933897', 'ASPINDALE District, Zimbabwe', '', '0', 'J5-ZW-HAR-033', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-35', 'SUNSIGHT', 'HARARE', 'Zimbabwe', 'MIRRIAM', '0711691740', 'ASPINDALE District, Zimbabwe', '', '0', 'J5-ZW-HAR-034', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-36', 'WARREN PARK D', 'HARARE', 'Zimbabwe', 'TABETH', '0711691740', 'ASPINDALE District, Zimbabwe', '', '0', 'J5-ZW-HAR-035', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-37', 'ZENGEZA 4', 'HARARE', 'Zimbabwe', 'KUDZI MWANDIWANA', '0771516698', 'CHITUNGWIZA District, Zimbabwe', '', '0', 'J5-ZW-HAR-036', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-38', 'ST MARRYS', 'HARARE', 'Zimbabwe', 'BLESSING', '0781811302', 'CHITUNGWIZA District, Zimbabwe', '', '0', 'J5-ZW-HAR-037', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-39', 'UNIT L', 'HARARE', 'Zimbabwe', 'TICHAREVA GAZA', '0782592520', 'CHITUNGWIZA District, Zimbabwe', '', '0', 'J5-ZW-HAR-038', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-40', 'UNIT N', 'HARARE', 'Zimbabwe', 'PATIENCE MATAONA', '0784212000', 'CHITUNGWIZA District, Zimbabwe', '', '0', 'J5-ZW-HAR-039', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-41', 'RETREAT', 'HARARE', 'Zimbabwe', 'TATENDA', '0774588178', 'RETREAT District, Zimbabwe', '', '0', 'J5-ZW-HAR-040', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-harare-42', 'CHINHANGA', 'HARARE', 'Zimbabwe', 'VONGAI', '0773399099', 'RETREAT District, Zimbabwe', '', '0', 'J5-ZW-HAR-041', 'Live', '2026', 'Imported from PROPHETS DATA.xls - HARARE', false),
  ('zw-masvingo-4', 'MASVINGO C', 'MASVINGO', 'Zimbabwe', 'SURPRISE MADYAGWAI', '0788849166', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-001', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-5', 'MANYAMA', 'MASVINGO', 'Zimbabwe', 'STELLA CHEMVUME', '0782630153', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-002', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-6', 'MASVINGO B', 'MASVINGO', 'Zimbabwe', 'TANATSWA MANGENA', '0777709669', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-003', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-7', 'MASVINGO A', 'MASVINGO', 'Zimbabwe', 'PAULINE MUGUMISI', '0789419485', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-004', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-8', 'BHUKA', 'MASVINGO', 'Zimbabwe', 'KUDAKWASHE HWATA', '0771380126', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-005', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-9', 'STEVEN', 'MASVINGO', 'Zimbabwe', 'LINDSAY MAGEZINI', '0777731787', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-006', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-10', 'SESE', 'MASVINGO', 'Zimbabwe', 'TRYMORE CHIDAU', '0788233084', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-007', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-11', 'RHODENE', 'MASVINGO', 'Zimbabwe', 'MARY MUNYANYI', '0774032922', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-008', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-12', 'MASHAVA A', 'MASVINGO', 'Zimbabwe', 'ENOCK', '0789360470', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-009', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-13', 'ZIMUTO CYDIN', 'MASVINGO', 'Zimbabwe', '', '', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-010', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-14', 'ZIMUTO MAHOTO', 'MASVINGO', 'Zimbabwe', 'JAMESON MUNSAKA', '0777749936', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-011', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-15', 'NEMAMWA', 'MASVINGO', 'Zimbabwe', 'TAFADZWANASHE NJUGA', '0785805888', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-012', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-16', 'MADAMOMBE', 'MASVINGO', 'Zimbabwe', 'GIFT BOPE', '0774413911', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-013', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-17', 'MASHAVA SUPA', 'MASVINGO', 'Zimbabwe', 'DADI TAMIRA', '0775522462', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-014', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-18', 'MASHAVA B', 'MASVINGO', 'Zimbabwe', 'BIAN MAKANYAMBI', '0772464268', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-015', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-19', 'CHIKARUDZO', 'MASVINGO', 'Zimbabwe', 'CATHRINE CHINOUNYE', '0774893743', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-016', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-20', 'CHARUMBIRA', 'MASVINGO', 'Zimbabwe', 'WADZANAI MUSARAFU', '0779721223', 'MASVINGO District, Zimbabwe', '', '0', 'J5-ZW-MAS-017', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-21', 'DETOYI', 'MASVINGO', 'Zimbabwe', 'TENDAI MANGAVA', '0781875844', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-018', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-22', 'MAWERE', 'MASVINGO', 'Zimbabwe', 'GODFREY MACHIYA', '0781622085', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-019', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-23', 'JERERA A', 'MASVINGO', 'Zimbabwe', 'NYARADZAI MABUKWA', '0788344275', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-020', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-24', 'CHIPFUTI', 'MASVINGO', 'Zimbabwe', 'NESTA MARANGE', '0776886836', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-021', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-25', 'NEMATAVANDA', 'MASVINGO', 'Zimbabwe', 'PANASHE NYATSANZA', '', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-022', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-26', '4 MILES', 'MASVINGO', 'Zimbabwe', 'LOICE SENEDZAI', '0785238008', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-023', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-27', 'JERERA B', 'MASVINGO', 'Zimbabwe', 'OPHIAS MADLIWA', '0788930663', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-024', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-28', 'NDANGA', 'MASVINGO', 'Zimbabwe', 'TADIWANASHE MWATSIKA', '0780009849', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-025', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-29', 'CHINORUMBA', 'MASVINGO', 'Zimbabwe', 'GODFREY BERNARD', '0783864985', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-026', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-30', 'CHIVAMBA', 'MASVINGO', 'Zimbabwe', 'ENOCK KARUMBIDZA', '0781300120', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-027', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-31', 'MUSARAVA', 'MASVINGO', 'Zimbabwe', 'ALEX MUPANEDENGU', '0781551446', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-028', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-32', 'GUMBO', 'MASVINGO', 'Zimbabwe', 'ABEL ALBERTO', '0789472251', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-029', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-33', 'COTTCO', 'MASVINGO', 'Zimbabwe', '', '', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-030', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-34', 'JUDEA', 'MASVINGO', 'Zimbabwe', '', '', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-031', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-35', 'RUGARE', 'MASVINGO', 'Zimbabwe', '', '', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-032', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-36', 'NYABOKWE', 'MASVINGO', 'Zimbabwe', 'RICHARD SANDE', '0789181307', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-033', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-37', 'VEZA', 'MASVINGO', 'Zimbabwe', '', '', 'ZAKA District, Zimbabwe', '', '0', 'J5-ZW-MAS-034', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-38', 'SKUTA', 'MASVINGO', 'Zimbabwe', 'DOCTOR CHINOERA', '0781979295', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-035', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-39', 'FILABUSI', 'MASVINGO', 'Zimbabwe', 'TALENT MBAYI', '0773657186', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-036', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-40', 'YORKO', 'MASVINGO', 'Zimbabwe', 'PAULINE CHIRENDA', '0774425296', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-037', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-41', 'MBERENGWA OFFICE', 'MASVINGO', 'Zimbabwe', 'JAMES ZIMUNYA', '0785094332', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-038', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-42', 'NKANKEZI', 'MASVINGO', 'Zimbabwe', '', '07', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-039', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-43', 'VANGUARD', 'MASVINGO', 'Zimbabwe', 'RUIZ BOBO', '07', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-040', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-44', 'BVUTE', 'MASVINGO', 'Zimbabwe', 'CHRISTINE CHAGWIZA', '0776321087', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-041', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-45', 'NETAR', 'MASVINGO', 'Zimbabwe', '', '', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-042', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-46', 'MBALABALA', 'MASVINGO', 'Zimbabwe', 'ASHLOCK MANDIPAUSHE', '0777974249', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-043', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-47', 'BMINE', 'MASVINGO', 'Zimbabwe', 'DANIEL KANYUNGWE', '0786980191', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-044', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-48', 'PHONEX', 'MASVINGO', 'Zimbabwe', 'ALPHA CHADEMANA', '0789092387', 'MBERENGWA District, Zimbabwe', '', '0', 'J5-ZW-MAS-045', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-49', 'GUTU CENTER', 'MASVINGO', 'Zimbabwe', 'BRIGHTON MUTASA', '0777982138', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-046', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-50', 'CHATSWORTHS', 'MASVINGO', 'Zimbabwe', 'SIMBARASHE MVUKWE', '0780675579', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-047', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-51', 'MAUNGWA', 'MASVINGO', 'Zimbabwe', 'TERRENCE SANYAMANDWE', '0785496070', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-048', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-52', 'MUCHECHETE', 'MASVINGO', 'Zimbabwe', 'JONATHAN LUNGA', '0784157664', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-049', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-53', 'ZVAVAHERA', 'MASVINGO', 'Zimbabwe', 'ONIAS', '0780425234', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-050', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-54', 'MUSHAYAVANHU', 'MASVINGO', 'Zimbabwe', 'SOUL CHIMBARARA', '0771199909', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-051', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-55', 'GONYE', 'MASVINGO', 'Zimbabwe', '', '', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-052', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-56', 'HUNDUZA', 'MASVINGO', 'Zimbabwe', 'ALFRED MANYASIRE', '0782465155', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-053', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-57', 'CHISHECHE', 'MASVINGO', 'Zimbabwe', 'LOVEMORE TAPENYAMA', '0785694900', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-054', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-58', 'BHASERA', 'MASVINGO', 'Zimbabwe', 'ASHLEY MHEMBWE', '0788724131', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-055', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-59', 'TACHI', 'MASVINGO', 'Zimbabwe', 'THOMAS TOFARASEI', '0774792633', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-056', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-60', 'GUTU B', 'MASVINGO', 'Zimbabwe', 'LENNY', '', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-057', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-61', 'NERUPIRI', 'MASVINGO', 'Zimbabwe', 'RACHEL POPI', '0785085701', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-058', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-62', 'CHITSA', 'MASVINGO', 'Zimbabwe', 'NYASHA LEOKEN', '0771360127', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-059', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-63', 'MUSHWAYI', 'MASVINGO', 'Zimbabwe', 'ABEL MUFARI', '0779644060', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-060', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-64', 'CHAGWIZA', 'MASVINGO', 'Zimbabwe', 'MOREST JAMUNI', '0780197735', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-061', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-65', 'MUGONI', 'MASVINGO', 'Zimbabwe', 'LOYD CHARABGA', '0782314741', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-062', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-66', 'MUTEMA', 'MASVINGO', 'Zimbabwe', 'MISHECK KARONGA', '0774881976', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-063', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-67', 'MATIZHA', 'MASVINGO', 'Zimbabwe', 'SHYLET BISON', '0778771586', 'GUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-064', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-68', 'NGUNDU', 'MASVINGO', 'Zimbabwe', 'NOMORE KURAI', '0778782663', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-065', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-69', 'RUTENGA', 'MASVINGO', 'Zimbabwe', 'JOSEPH MANDINGINDO', '0780694864', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-066', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-70', 'LUNDI', 'MASVINGO', 'Zimbabwe', 'WASHINGTON MUWONI', '0784003366', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-067', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-71', 'MARANDA TURN', 'MASVINGO', 'Zimbabwe', 'PETER ZINYARIMWE', '0711835974', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-068', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-72', 'ZIVUKU', 'MASVINGO', 'Zimbabwe', 'CUTHBERT MHLANGA', '0773746011', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-069', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-73', 'SHONGAMITI', 'MASVINGO', 'Zimbabwe', '', '', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-070', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-74', 'RENCO MINE', 'MASVINGO', 'Zimbabwe', 'SHOW TARUVINGA', '0789341496', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-071', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-75', 'RUPIKE', 'MASVINGO', 'Zimbabwe', 'CONSTANCE TSIGO', '0774716489', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-072', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-76', 'MARANDA DINHE', 'MASVINGO', 'Zimbabwe', 'TiNOTENDA TADIWA MUPFEKA', '0777508156', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-073', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-77', 'GORORO', 'MASVINGO', 'Zimbabwe', 'SHELTON MAPOSA', '07', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-074', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-78', 'MUSEBA', 'MASVINGO', 'Zimbabwe', 'PANACHE NHONE', '07', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-075', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-79', 'MARINGIRE', 'MASVINGO', 'Zimbabwe', 'DAVID CHAWAPIWA', '0778968876', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-076', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-80', 'MUSVOVI', 'MASVINGO', 'Zimbabwe', 'CLOUD MAFATI', '0776006667', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-077', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-81', 'NESHURO', 'MASVINGO', 'Zimbabwe', 'PERPETUA KAMURAI', '0776769053', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-078', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-82', 'CHIKOMBEDZI', 'MASVINGO', 'Zimbabwe', 'PHILLIP', '0774633645', 'MWENEZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-079', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-83', 'CHIGOMBA', 'MASVINGO', 'Zimbabwe', 'BERNARD ZENGENI', '0774232161', 'ZVISHAVANE District, Zimbabwe', '', '0', 'J5-ZW-MAS-080', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-84', '4 MILES', 'MASVINGO', 'Zimbabwe', 'CARLOS MOYO', '0771057263', 'ZVISHAVANE District, Zimbabwe', '', '0', 'J5-ZW-MAS-081', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-85', 'VUGWI', 'MASVINGO', 'Zimbabwe', 'FARAI GOREMUCHECHE', '0781705898', 'ZVISHAVANE District, Zimbabwe', '', '0', 'J5-ZW-MAS-082', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-86', 'SIBOZA', 'MASVINGO', 'Zimbabwe', 'GODKNOWS MAGWIDI', '0784111421', 'ZVISHAVANE District, Zimbabwe', '', '0', 'J5-ZW-MAS-083', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-87', 'CHITOWA', 'MASVINGO', 'Zimbabwe', 'ATANAS JUNIOR', '0789603417', 'ZVISHAVANE District, Zimbabwe', '', '0', 'J5-ZW-MAS-084', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-88', 'MAGLASS', 'MASVINGO', 'Zimbabwe', 'MOREBY', '', 'ZVISHAVANE District, Zimbabwe', '', '0', 'J5-ZW-MAS-085', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-89', 'CHIREDZI LYONAIS', 'MASVINGO', 'Zimbabwe', 'BRIAN MASENDA', '0785354846', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-086', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-90', 'TRIANGLE A', 'MASVINGO', 'Zimbabwe', '', '', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-087', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-91', 'CHISASE', 'MASVINGO', 'Zimbabwe', 'JACOB MUYAMBO', '0776886461', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-088', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-92', 'MKWASINE B', 'MASVINGO', 'Zimbabwe', 'EFFORT TAPUWA', '0780328091', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-089', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-93', 'TRIANGLE B', 'MASVINGO', 'Zimbabwe', 'EMMANUEL SITHOLE', '0786634791', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-090', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-94', 'SAMBA RANCH', 'MASVINGO', 'Zimbabwe', '', '', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-091', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-95', 'MASHOKO', 'MASVINGO', 'Zimbabwe', 'CONWELL MADZIVIRIDZE', '0776536861', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-092', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-96', 'MASEKESA', 'MASVINGO', 'Zimbabwe', 'NYARADZAI MAPANGA', '0784842250', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-093', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-97', 'MKWASINE A', 'MASVINGO', 'Zimbabwe', 'ALBERTO MARWIZI', '0789190082', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-094', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-98', 'RENCO TURN', 'MASVINGO', 'Zimbabwe', 'PANGANAI MATSAURE', '0776737051', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-095', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-99', 'GUTSARUZHINJI', 'MASVINGO', 'Zimbabwe', 'ELISHA CHIWOMO', '0777891540', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-096', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-100', 'NYANGAMBE', 'MASVINGO', 'Zimbabwe', '', '', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-097', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-101', 'VHENEKA B', 'MASVINGO', 'Zimbabwe', '-', '', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-098', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-102', 'VHENEKA C', 'MASVINGO', 'Zimbabwe', '-', '', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-099', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-103', 'VHENEKA A', 'MASVINGO', 'Zimbabwe', 'PERSEVERANCE CHIKOMO', '0773488661', 'CHIREDZI District, Zimbabwe', '', '0', 'J5-ZW-MAS-100', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-104', 'NYIKA', 'MASVINGO', 'Zimbabwe', 'LASTWELL MAISIRE', '0779792093', 'BIKITA District, Zimbabwe', '', '0', 'J5-ZW-MAS-101', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-105', 'MUPAMAONDE', 'MASVINGO', 'Zimbabwe', 'RUMBIDZAI MUCHAZONDIDA', '0771901118', 'BIKITA District, Zimbabwe', '', '0', 'J5-ZW-MAS-102', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-106', 'SILVEIRA', 'MASVINGO', 'Zimbabwe', 'ABINEL FORCE', '0774249057', 'BIKITA District, Zimbabwe', '', '0', 'J5-ZW-MAS-103', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-107', 'PAMUSHANA', 'MASVINGO', 'Zimbabwe', 'PEPUKAI GONYE', '0785237955', 'BIKITA District, Zimbabwe', '', '0', 'J5-ZW-MAS-104', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-108', 'MAKUVAZA', 'MASVINGO', 'Zimbabwe', 'NATHAN CHATODZA', '0771787315', 'BIKITA District, Zimbabwe', '', '0', 'J5-ZW-MAS-105', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-109', 'JENETI', 'MASVINGO', 'Zimbabwe', 'TATENDA CHIKUNDA', '0782725708', 'BIKITA District, Zimbabwe', '', '0', 'J5-ZW-MAS-106', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-110', 'CHIREMWAREMWA', 'MASVINGO', 'Zimbabwe', 'JONATHAN CHIDEYA', '0774897037', 'BIKITA District, Zimbabwe', '', '0', 'J5-ZW-MAS-107', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-111', 'NJARAVANI', 'MASVINGO', 'Zimbabwe', 'LONIAS NDLOVU', '', 'BIKITA District, Zimbabwe', '', '0', 'J5-ZW-MAS-108', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-112', 'PADARE', 'MASVINGO', 'Zimbabwe', 'EMMANUEL', '0779328566', 'BIKITA District, Zimbabwe', '', '0', 'J5-ZW-MAS-109', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-113', 'CHIVI CENTER', 'MASVINGO', 'Zimbabwe', 'PHILDA MUSIZVINGOZA', '0774119486', 'CHIVI District, Zimbabwe', '', '0', 'J5-ZW-MAS-110', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-114', 'CHIBI TURN', 'MASVINGO', 'Zimbabwe', 'JACOB MURIYA', '0784002442', 'CHIVI District, Zimbabwe', '', '0', 'J5-ZW-MAS-111', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-115', 'MHANDAMABWE', 'MASVINGO', 'Zimbabwe', 'RAFIK FELEX', '0789525126', 'CHIVI District, Zimbabwe', '', '0', 'J5-ZW-MAS-112', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-116', 'TAKAVARASHA', 'MASVINGO', 'Zimbabwe', 'KEZIYA MUGOMERI', '', 'CHIVI District, Zimbabwe', '', '0', 'J5-ZW-MAS-113', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-masvingo-117', 'DAVIRA', 'MASVINGO', 'Zimbabwe', 'CHIPO MUNDUMA', '0779958856', 'CHIVI District, Zimbabwe', '', '0', 'J5-ZW-MAS-114', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASVINGO', false),
  ('zw-midlands-3', 'CANAAN', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-001', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-4', 'PEAKMINE', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-002', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-5', 'FALCON', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-003', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-6', 'RUCHANYU', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-004', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-7', 'GWANZA', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-005', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-8', 'CHIRONDE', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-006', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-9', 'CHACHACHA', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-007', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-11', 'MAKUSHA', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-008', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-12', 'MUSASA', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-009', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-13', 'CHIKATO', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-010', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-14', 'TONGOGARA', 'MIDLANDS', 'Zimbabwe', '', '', 'SHURUGWI District, Zimbabwe', '', '0', 'J5-ZW-MID-011', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-15', 'MBIZO A', 'MIDLANDS', 'Zimbabwe', 'TANYARADZWA', '0780166558', 'KWEKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-012', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-16', 'MBIZO B', 'MIDLANDS', 'Zimbabwe', 'AARON', '0781782578', 'KWEKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-013', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-17', 'MBIZO C', 'MIDLANDS', 'Zimbabwe', 'NOMATTER', '0773746485', 'KWEKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-014', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-18', 'AMAVENI', 'MIDLANDS', 'Zimbabwe', 'BIG BOY', '0782167408', 'KWEKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-015', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-19', 'REDCLIFF', 'MIDLANDS', 'Zimbabwe', 'BLESSING', '0716712474', 'KWEKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-016', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-20', 'ROASTING PLANT', 'MIDLANDS', 'Zimbabwe', 'MARIA', '0782110641', 'KWEKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-017', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-21', 'TYGERIFF', 'MIDLANDS', 'Zimbabwe', '', '', 'KWEKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-018', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-22', 'TORWOOD', 'MIDLANDS', 'Zimbabwe', 'STERN', '0781076672', 'KWEKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-019', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-23', 'EMPRESS', 'MIDLANDS', 'Zimbabwe', 'BRIGHTON', '0778061307', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-020', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-24', 'ZHOMBE', 'MIDLANDS', 'Zimbabwe', '', '', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-021', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-25', 'GOKWE D', 'MIDLANDS', 'Zimbabwe', 'SPIWE', '0771362513', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-022', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-26', 'GOKWE A', 'MIDLANDS', 'Zimbabwe', 'BLESSED', '0771088260', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-023', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-27', 'GOKWE B', 'MIDLANDS', 'Zimbabwe', 'KUZIVA', '0782349444', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-024', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-28', 'GOKWE C', 'MIDLANDS', 'Zimbabwe', 'TRACY', '0787336236', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-025', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-29', 'RAJI', 'MIDLANDS', 'Zimbabwe', '', '', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-026', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-30', 'CHITEKETE', 'MIDLANDS', 'Zimbabwe', '', '', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-027', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-31', 'TOTORORO', 'MIDLANDS', 'Zimbabwe', 'CONSTANCE', '078363675', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-028', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-32', 'BOMBA', 'MIDLANDS', 'Zimbabwe', '', '', 'GOKWE District, Zimbabwe', '', '0', 'J5-ZW-MID-029', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-33', 'CLAREMONT', 'MIDLANDS', 'Zimbabwe', 'MAXWELL GWITIRI', '0784206574', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-030', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-34', 'MAGRAVEL', 'MIDLANDS', 'Zimbabwe', '', '', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-031', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-35', 'MKOBA A (16)', 'MIDLANDS', 'Zimbabwe', 'THABANI MUPANDE', '0785253998', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-032', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-36', 'MKOBA B (19)', 'MIDLANDS', 'Zimbabwe', 'CHRISPEN CHIHEYA', '0777300118', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-033', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-37', 'BRISTOL', 'MIDLANDS', 'Zimbabwe', 'NYASHA NKOMO', '0782862037', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-034', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-38', 'MAKULAMBILA', 'MIDLANDS', 'Zimbabwe', 'ANORLD', '0787930462', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-035', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-39', 'MABOLENI', 'MIDLANDS', 'Zimbabwe', 'JERRY', '0771421605', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-036', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-40', 'SENGA', 'MIDLANDS', 'Zimbabwe', 'SARAH MBANDURE', '0779962464', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-037', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-41', 'SINO', 'MIDLANDS', 'Zimbabwe', '', '', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-038', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-42', 'CONCELLAR', 'MIDLANDS', 'Zimbabwe', 'GLEN MARIRA', '', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-039', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-43', 'MANDINDINDI', 'MIDLANDS', 'Zimbabwe', 'BRIGHTON ANTONIO', '0787860181', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-040', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-44', 'RIDGEMONT', 'MIDLANDS', 'Zimbabwe', 'MIRIAM MATONGO', '0783436358', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-041', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-45', 'LOWER GWERU A', 'MIDLANDS', 'Zimbabwe', 'THERESA NUNDODZI', '0777273234', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-042', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-46', 'SHAGARI', 'MIDLANDS', 'Zimbabwe', 'SIMBARASHE CHAPINGA', '0776255531', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-043', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-47', 'MATAMBO', 'MIDLANDS', 'Zimbabwe', 'DORCAS CHIMONYO', '0774847298', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-044', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-48', 'ROMA SILOBELA', 'MIDLANDS', 'Zimbabwe', 'SAYMORE', '', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-045', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-49', 'LOWER GWERU TURN', 'MIDLANDS', 'Zimbabwe', 'STEPHEN CHIMOMBO', '0779954175', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-046', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-50', 'ZIBOMVU', 'MIDLANDS', 'Zimbabwe', '', '', 'GWERU District, Zimbabwe', '', '0', 'J5-ZW-MID-047', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-51', 'HOLLYLAND', 'MIDLANDS', 'Zimbabwe', 'GETRUDE MATIMBA', '0771123221', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-048', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-55', 'BASE CANAAN', 'MIDLANDS', 'Zimbabwe', 'GRACE', '0779044716', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-049', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-56', 'FAREFIELDS', 'MIDLANDS', 'Zimbabwe', 'INNOCENT MUGWAMBI', '', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-050', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-57', 'NYAGARI', 'MIDLANDS', 'Zimbabwe', 'RHODA TINARWO', '0773027955', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-051', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-58', 'LALAPANZI', 'MIDLANDS', 'Zimbabwe', 'DENZEL NDORO', '', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-052', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-59', 'CROSS', 'MIDLANDS', 'Zimbabwe', 'LIBERTY MUYAMBO', '0775544805', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-053', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-60', 'HAMA', 'MIDLANDS', 'Zimbabwe', 'BEKITHEMBA', '0782672388', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-054', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-61', 'MAPIRAVANA', 'MIDLANDS', 'Zimbabwe', 'TANAKA ZINYAWU', '0771878167', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-055', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-62', 'CHAKA', 'MIDLANDS', 'Zimbabwe', 'MARY MARIGWA', '', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-056', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-midlands-63', 'MAVISE', 'MIDLANDS', 'Zimbabwe', 'AILEEN BIRIYADI', '0775949066', 'MVUMA District, Zimbabwe', '', '0', 'J5-ZW-MID-057', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MIDLANDS', false),
  ('zw-mashwest-3', 'NORTON A', 'MASHWEST', 'Zimbabwe', 'PANASHE', '', 'NORTON District, Zimbabwe', '', '0', 'J5-ZW-MAS-001', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-4', 'NORTON B', 'MASHWEST', 'Zimbabwe', 'KUDAKWASHE', '', 'NORTON District, Zimbabwe', '', '0', 'J5-ZW-MAS-002', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-5', 'HALFWAY', 'MASHWEST', 'Zimbabwe', 'GRACE', '', 'NORTON District, Zimbabwe', '', '0', 'J5-ZW-MAS-003', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-6', 'NYAGA CITY', 'MASHWEST', 'Zimbabwe', 'MASI', '', 'NORTON District, Zimbabwe', '', '0', 'J5-ZW-MAS-004', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-7', 'MUROMBEDZI', 'MASHWEST', 'Zimbabwe', 'ARNOLD', '', 'NORTON District, Zimbabwe', '', '0', 'J5-ZW-MAS-005', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-8', 'KARIBA A', 'MASHWEST', 'Zimbabwe', 'TINASHE', '', 'KARIBA District, Zimbabwe', '', '0', 'J5-ZW-MAS-006', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-9', 'KARIBA B', 'MASHWEST', 'Zimbabwe', 'JOB', '', 'KARIBA District, Zimbabwe', '', '0', 'J5-ZW-MAS-007', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-10', 'NYAMAKATE', 'MASHWEST', 'Zimbabwe', 'RIBEL', '', 'KARIBA District, Zimbabwe', '', '0', 'J5-ZW-MAS-008', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-11', 'CHIRUNDU', 'MASHWEST', 'Zimbabwe', 'MIKA', '', 'KARIBA District, Zimbabwe', '', '0', 'J5-ZW-MAS-009', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-12', 'ZVIPANE', 'MASHWEST', 'Zimbabwe', 'PANASHE', '', 'KARIBA District, Zimbabwe', '', '0', 'J5-ZW-MAS-010', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-13', 'MAGUNJE', 'MASHWEST', 'Zimbabwe', 'HONEST', '', 'KARIBA District, Zimbabwe', '', '0', 'J5-ZW-MAS-011', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-14', 'KARIBA C', 'MASHWEST', 'Zimbabwe', 'PANASHE', '', 'KARIBA District, Zimbabwe', '', '0', 'J5-ZW-MAS-012', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-15', 'BIRIMAHWE', 'MASHWEST', 'Zimbabwe', 'MOSES', '', 'KARIBA District, Zimbabwe', '', '0', 'J5-ZW-MAS-013', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-16', 'KAROI A', 'MASHWEST', 'Zimbabwe', 'CRAIG', '', 'KAROI District, Zimbabwe', '', '0', 'J5-ZW-MAS-014', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-17', 'KAROI B', 'MASHWEST', 'Zimbabwe', 'KUDAKWASHE', '', 'KAROI District, Zimbabwe', '', '0', 'J5-ZW-MAS-015', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-18', 'KASIMHURE', 'MASHWEST', 'Zimbabwe', 'GRACE', '', 'KAROI District, Zimbabwe', '', '0', 'J5-ZW-MAS-016', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-19', 'CHINHOYI A', 'MASHWEST', 'Zimbabwe', 'SIMBA', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-017', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-20', 'CHINHOYI B', 'MASHWEST', 'Zimbabwe', 'ROBERT', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-018', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-21', 'CHINHOYI C', 'MASHWEST', 'Zimbabwe', 'LANGTON', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-019', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-22', 'MHANGURA A', 'MASHWEST', 'Zimbabwe', 'CHENAI', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-020', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-23', 'MHANGURA B', 'MASHWEST', 'Zimbabwe', 'LOVEMORE', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-021', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-24', 'MHANGURA C', 'MASHWEST', 'Zimbabwe', 'SIMBA', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-022', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-25', 'ALASKA', 'MASHWEST', 'Zimbabwe', 'GIFT', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-023', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-26', 'RAFINGORA', 'MASHWEST', 'Zimbabwe', 'SHINGI', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-024', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-27', 'TRILON', 'MASHWEST', 'Zimbabwe', 'GETRUDE', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-025', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-28', 'BANKET', 'MASHWEST', 'Zimbabwe', 'MUNASHE', '', 'CHINHOYI District, Zimbabwe', '', '0', 'J5-ZW-MAS-026', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-29', 'RIMUKA A', 'MASHWEST', 'Zimbabwe', 'ITAI', '', 'KADOMA District, Zimbabwe', '', '0', 'J5-ZW-MAS-027', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-30', 'MORNINGTON', 'MASHWEST', 'Zimbabwe', 'KUDZI', '', 'KADOMA District, Zimbabwe', '', '0', 'J5-ZW-MAS-028', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-31', 'PIXI COMBI', 'MASHWEST', 'Zimbabwe', 'JUSTICE', '', 'KADOMA District, Zimbabwe', '', '0', 'J5-ZW-MAS-029', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-32', 'PATCHWAY', 'MASHWEST', 'Zimbabwe', 'DIVINIA', '', 'KADOMA District, Zimbabwe', '', '0', 'J5-ZW-MAS-030', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-33', 'PINGO', 'MASHWEST', 'Zimbabwe', 'TRACY', '', 'KADOMA District, Zimbabwe', '', '0', 'J5-ZW-MAS-031', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-34', 'INGEZI', 'MASHWEST', 'Zimbabwe', 'MAGGIE', '', 'KADOMA District, Zimbabwe', '', '0', 'J5-ZW-MAS-032', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-35', 'BY', 'MASHWEST', 'Zimbabwe', 'ALEXANDRE', '', 'KADOMA District, Zimbabwe', '', '0', 'J5-ZW-MAS-033', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-36', 'VERNICE', 'MASHWEST', 'Zimbabwe', 'VERNICE', '', 'KADOMA District, Zimbabwe', '', '0', 'J5-ZW-MAS-034', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-37', 'CHEGUTU A', 'MASHWEST', 'Zimbabwe', 'CUTHBERT', '', 'CHEGUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-035', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-38', 'CHEGUTU B', 'MASHWEST', 'Zimbabwe', 'CHIDO', '', 'CHEGUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-036', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-39', 'CHAKARI A', 'MASHWEST', 'Zimbabwe', 'MELUSI', '', 'CHEGUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-037', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-40', 'CHAKARI B', 'MASHWEST', 'Zimbabwe', 'WINSTEG', '', 'CHEGUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-038', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-41', 'MIRIAM', 'MASHWEST', 'Zimbabwe', '', '', 'CHEGUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-039', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-42', 'CHIPO', 'MASHWEST', 'Zimbabwe', '', '', 'CHEGUTU District, Zimbabwe', '', '0', 'J5-ZW-MAS-040', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-43', 'TURF', 'MASHWEST', 'Zimbabwe', 'TAKUDZWA', '', 'MHONDORO District, Zimbabwe', '', '0', 'J5-ZW-MAS-041', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-44', 'GREEN', 'MASHWEST', 'Zimbabwe', 'CHONI', '', 'MHONDORO District, Zimbabwe', '', '0', 'J5-ZW-MAS-042', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false),
  ('zw-mashwest-45', 'CHINGWERE', 'MASHWEST', 'Zimbabwe', 'MEMORY', '', 'MHONDORO District, Zimbabwe', '', '0', 'J5-ZW-MAS-043', 'Live', '2026', 'Imported from PROPHETS DATA.xls - MASHWEST', false)
on conflict (id) do update set
  name = excluded.name,
  province = excluded.province,
  country = excluded.country,
  prophet = excluded.prophet,
  phone = excluded.phone,
  address = excluded.address,
  gps = excluded.gps,
  members = excluded.members,
  code = excluded.code,
  status = excluded.status,
  founded = excluded.founded,
  notes = excluded.notes,
  is_hq = excluded.is_hq;
