-- Imported from bulawayo%20province.pdf.
-- Unclear names, phone numbers, and amounts are preserved as marked or blank.
-- Duplicate source numbers are retained with suffixed IDs.
-- Uses the shared protected Burial Society registry table.

insert into public.burial_society_member_registry
  (id, source_number, full_name, phone, amount_paid, linked, linked_member_id, linked_auth_user_id, source)
values
  ('bulawayo-burial-001', 1, 'Ciswell Matore', '0713133354', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-002', 2, 'Stanford Molebe', '0168011226', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-003', 3, 'Janet Nhamalo', '0711921861', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-004', 4, 'France Dube', '0711021416', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-005', 5, 'Marvelous Moyo', '0718368397', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-006', 6, 'Emelly Moyo', '0713960465', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-007', 7, 'Esnath Moyo', '0710115206', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-008', 8, 'Trandline Phiri', '0769271841', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-009', 9, 'Nothando Shumba', '0719911441', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-010', 10, 'Chengei Sibanda', '0715933196', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-011', 11, 'Miriam Moyo', '071544240', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-012', 12, 'Hopewell Hove', '07155219401', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-013', 13, 'Timmy', '071951324', '', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-013-2', 13, 'Dumisani Sibanda', '0741418610', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-014', 14, 'Senzeni Nyoni', '0718912448', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-015', 15, 'Aurilicia Ndlovu', '0713284811', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-016', 16, 'Abigail Masina', '0712215614', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-017', 17, 'Kelvin Sibanda', '0760502431', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-018', 18, 'Saimore Zimi', '0760034113', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-019', 19, 'Andile Sibanda', '0718835814', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-020', 20, 'Holly Hunierega', '0764702134', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-021', 21, 'Blessing Ndhlukula', '0713730816', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-022', 22, 'Velani Sibanda', '0710225162', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-023', 23, 'Ntombi Moyo', '0718391369', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-024', 24, 'Cecion Ndlovu', '0714461217', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-025', 25, 'Christopher Shongwe', '0710272684', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-026', 26, 'Sheila Nkala', '0715114804', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-027', 27, 'Netsai Mabhunu?', '0713553890', '14.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-028', 28, 'Deliwe Ncube', '0714641526', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-029', 29, 'Ruvareche Mucumbe', '0711603181', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-030', 30, 'Ntombi Nyathi', '07102410001', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-031', 31, 'Hpros Nkala', '0719333180', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-032', 32, 'Eelson Moyo', '0718516431', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-033', 33, 'Angelinah Nyoni', '0713784695', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-034', 34, 'Theresa Sibanda', '0716562376', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-035', 35, 'Khululeku? Ncube', '0714786255', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-036', 36, 'Faith Sibanda', '0711900833', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-037', 37, 'Reason Musupi', '0712151626', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-038', 38, 'Cynthia Moyo', '0710155626', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-039', 39, 'Violet Tshuma', '0715917385', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-040', 40, 'Dorcas Moyo', '0713534664', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-041', 41, 'Gladys Chiweshe', '0715182647', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-042', 42, 'Sipiso Mashuhume', '0714481468', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-043', 43, 'Sithandekile Tshuma', '0711841322', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-044', 44, 'Stanford Ngwenya', '0712830303', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-045', 45, 'Sithembiso Ndlovu', '0716241683', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-046', 46, 'Shantel Gweshe?', '0715594462', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-047', 47, 'Mkhululi Npofu', '0712164329', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-048', 48, 'Dumisile Ncube', '0716016493', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-049', 49, 'Memory Mathe', '0714320314', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-050', 50, 'Meslinda Lewis', '0712523725', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-051', 51, 'Elizabeth Chinyama', '0714913264', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-052', 52, 'Kudzirwa? Hunter', '071380126', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-053', 53, 'Evelyn Tiero', '0718739232', '', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-054', 54, 'Nelly Mpofu', '0711311153', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-055', 55, 'Nothando Sibanda', '0713873253', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-056', 56, 'Lilothi Ndlovu', '', '', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-057', 57, 'Mlcvel Dube', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-058', 58, 'Marnce Nyandoro', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-059', 59, 'Beauty Sibanda', '', '14.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-060', 60, 'Nyina Faw…?', '', '16.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-061', 61, 'Tsabiso Bayla', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-062', 62, 'Celsipe Sibanda', '', '20.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-063', 63, 'Eve Maza', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-064', 64, 'Mp… Mpofu', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-065', 65, 'Lind… Sibanda', '', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-066', 66, 'L… Ncube', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-067', 67, 'Sisel… Ncube', '', '36.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-068', 68, 'Virginia …', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-069', 69, 'Dorcas Sibanda', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-070', 70, 'Alfa Nkomo', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-071', 71, 'Sebekeile Ncube', '', '14.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-072', 72, 'Tamara Nkala', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-073', 73, 'Grace Mpofu', '', '8.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-074', 74, 'Tsabiso Bayla', '', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-075', 75, 'Florence Ncube', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-076', 76, 'Sithembile Sibanda', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-077', 77, 'Dumisile Ncube', '', '18.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-078', 78, 'Celyan Sibanda', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-079', 79, 'Mabie Phoko', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-080', 80, 'Ntombenhle Nyathi', '', '10.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-081', 81, 'Desire Rumb…', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-082', 82, 'Petronella Rusinwi', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-083', 83, 'Nobukhosi Ncube', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-084', 84, 'Nomsa Nkala', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-085', 85, 'Alfa Nkomo', '', '12.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-086', 86, 'Jolanda Nkala', '', '5.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-087', 87, 'Kalibari Moyo', '', '7.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-088', 88, 'Liloth Ndlovu', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-089', 89, 'Keswe Zulu', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-090', 90, 'Linneth Mpofu', '', '9.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-091', 91, 'Steezekile Ncube', '', '9.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-092', 92, 'Sithembiso Sibanda', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-093', 93, 'Sh…rose Ngwenya', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-094', 94, 'Evelyn Sibanda', '', '9.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-095', 95, 'Sipiso Sibanda', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-096', 96, 'Menchulo Ndlovu', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-097', 97, 'Nobuhle Sibanda', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-098', 98, 'Stanford Ngwenya', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-099', 99, 'Nobukhosi Ncube', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-100', 100, 'Reason Musupi', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-101', 101, 'France Dube', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-102', 102, 'Dorcas Moyo', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-103', 103, 'Mable Phoko', '', '15.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-104', 104, 'Esnath Moyo', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-105', 105, 'Kelvin Dube', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-106', 106, 'Kelvin Ngwenya', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-107', 107, 'Evelyn Moyo', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-108', 108, 'Hlabezisile Ndlovu', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-108-2', 108, 'Ayanda? Sibanda', '', '6.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-109', 109, 'Simbore… Sithole', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt'),
  ('bulawayo-burial-110', 110, 'Senzeni Nyoni', '', '3.00', false, null, null, 'bulawayo_province_burial_members_extracted.txt')
on conflict (id) do update set
  source_number = excluded.source_number,
  full_name = excluded.full_name,
  phone = excluded.phone,
  amount_paid = excluded.amount_paid,
  source = excluded.source,
  updated_at = now();
