-- Generated from Mozambique Branches.xls, sheet April 2026. Review before running in Supabase.

insert into public.branches
  (id, name, province, country, prophet, phone, address, gps, members, code, status, founded, notes, is_hq)
values
  ('mz-branch-001', 'Nhamadjessa', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-001', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-002', 'Nhauriri', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-002', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-003', 'Matsinhe', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-003', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-004', 'Vandizi', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-004', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-005', 'ADPP', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-005', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-006', '1 de Maio', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-006', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-007', 'Trinta e oito', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-007', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-008', '7 de Abril', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-008', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-009', 'Musangadzi', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-009', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-010', 'Central', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-010', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-011', 'Chigodore', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-011', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-012', 'Chinete', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-012', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-013', 'Macadeira', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-013', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-014', 'Mukombeze', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-014', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-015', 'Macate', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-015', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-016', 'Crusamento de TeTe', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-016', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-017', 'Belasi', 'MANICA', 'Mozambique', '', '', 'Chimoio, Mozambique', '', '0', 'J5-MZ-017', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-018', 'Mukwananda', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-018', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-019', 'Almeida', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-019', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-020', 'Raça', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-020', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-021', 'Josina Machel', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-021', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-022', 'Sambai', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-022', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-023', 'Machipanda', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-023', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-024', 'Mugoriondo', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-024', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-025', 'Penhalonga', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-025', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-026', 'Chadzuka', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-026', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-027', 'Chuwa', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-027', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-028', 'Mavonde', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-028', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-029', 'Messica', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-029', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-030', 'Messica 25', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-030', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-031', 'Ruaca', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-031', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-032', 'Bandula', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-032', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-033', 'Chicamba', 'MANICA', 'Mozambique', '', '', 'Manica District, Mozambique', '', '0', 'J5-MZ-033', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-034', 'Mupengo', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-034', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-035', 'Dacata', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-035', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-036', 'Goigoi', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-036', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-037', 'Mutowe', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-037', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-038', 'Chizango', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-038', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-039', 'Muthini', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-039', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-040', 'Muchenedzi A', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-040', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-041', 'Muchenedzi B', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-041', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-042', 'Espungabeira A', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-042', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-043', 'Espungabeira B', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-043', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-044', 'Mukarate', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-044', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-045', 'Dhoki', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-045', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-046', 'Gaha', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-046', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-047', 'Chingowe', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-047', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-048', 'Mude', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-048', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-049', 'Muwawa', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-049', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-050', 'Dombe', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-050', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-051', 'Machiri', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-051', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-052', 'Dimba utore', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-052', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-053', 'Central Mavuzi', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-053', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-054', 'Munyinga', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-054', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-055', '7 de Abril', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-055', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-056', 'Nyamawaya', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-056', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-057', 'Rotanda', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-057', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-058', 'Tsetsera', 'MANICA', 'Mozambique', '', '', 'Mossorize District, Mozambique', '', '0', 'J5-MZ-058', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-059', 'Machaze sede', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-059', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-060', 'Machaze Hospital', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-060', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-061', 'Chipuji', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-061', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-062', 'Bassane', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-062', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-063', 'Chipambleque', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-063', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-064', 'Chipopopo', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-064', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-065', 'Mutefu', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-065', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-066', 'Daladjive', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-066', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-067', 'Chidoko', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-067', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-068', 'Sambasoka', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-068', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-069', 'Mavende', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-069', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-070', 'Mussorobongo', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-070', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-071', 'Chiwawane', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-071', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-072', 'Chibuto', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-072', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-073', 'Thimbi Thimbi', 'MANICA', 'Mozambique', '', '', 'Machaze District, Mozambique', '', '0', 'J5-MZ-073', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-074', 'Catandica Sede', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-074', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-075', 'Sabao', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-075', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-076', 'Honde', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-076', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-077', 'Chuala', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-077', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-078', 'Panzi', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-078', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-079', 'Mutsinzi', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-079', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-080', 'Chindengue', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-080', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-081', 'Nhampassa', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-081', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-082', 'Cruzamento Macossa', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-082', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-083', 'Nhassakara', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-083', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-084', 'Gurro', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-084', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-085', 'Dunda', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-085', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-086', 'Macossa', 'MANICA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-086', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-087', 'Dondo A', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-087', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-088', 'Manga Mascarenha', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-088', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-089', 'Mutuwa', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-089', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-090', 'Xota', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-090', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-091', 'Nhamizua', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-091', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-092', 'Mobeira', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-092', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-093', 'Ceramica', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-093', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-094', 'Dondo B', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-094', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-095', 'Passagem de Nível', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-095', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-096', 'Mafambisse', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-096', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-097', 'Savane', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-097', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-098', 'Tica', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-098', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-099', 'Lamego', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-099', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-100', 'Nhamatanda A', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-100', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-101', 'Nhamatanda B', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-101', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-102', 'Nharuxonga', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-102', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-103', 'Xiluvo', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-103', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-104', 'Inchope', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-104', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-105', 'Muda Cereçao', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-105', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-106', 'Chibuto', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-106', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-107', 'Nhamabawe', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-107', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-108', 'Muxungue', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-108', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-109', 'Gonda', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-109', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-110', 'Mutindiri', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-110', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-111', 'Hode', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-111', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-112', 'Hamamba', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-112', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-113', 'Revuwe', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-113', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-114', 'Guruja', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-114', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-115', 'Guaraguara', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-115', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-116', 'Buzi', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-116', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-117', 'Bandua', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-117', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-118', 'Nova Sofala', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-118', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-119', 'Dhanga', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-119', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-120', 'Gorongoza A', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-120', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-121', 'Gorongoza B', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-121', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-122', 'Caia', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-122', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-123', 'Inhaminga', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-123', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-124', 'Maxixe', 'SOFALA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-124', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-125', 'Mpadue', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-125', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-126', 'Kwachena', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-126', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-127', 'Chingodzi', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-127', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-128', 'Seleste', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-128', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-129', 'Moatize A', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-129', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-130', 'Benga', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-130', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-131', 'Moatize B', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-131', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-132', 'Angonia', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-132', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-133', 'Zobwe', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-133', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-134', 'Mussakama', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-134', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-135', 'Songo', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-135', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-136', 'Chitima', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-136', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-137', 'Missawa', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-137', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-138', 'Chirodzi', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-138', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-139', 'Mazowe', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-139', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-140', 'Kuchamanom', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-140', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-141', 'Changara', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-141', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-142', 'Carata', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-142', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-143', 'Chiokompende', 'TETE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-143', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-144', 'Matola gare', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-144', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-145', '1 de Maio', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-145', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-146', 'Boane', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-146', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-147', 'Catembe', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-147', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-148', 'Ressano Garcia', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-148', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-149', 'Coca_Cola', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-149', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-150', 'Matola F', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-150', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-151', 'Muamba', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-151', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-152', 'Boquiso', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-152', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-153', 'Macia Xaixai', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-153', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-154', 'Matola rio', 'MAPUTO', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-154', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-155', 'Nanclue', 'NAMPULA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-155', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-156', 'Nampaco', 'NAMPULA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-156', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-157', 'Muatala', 'NAMPULA', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-157', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-158', 'Quelimane A', 'QUELIMANE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-158', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-159', 'Mocuba', 'QUELIMANE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-159', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-160', 'Massinga', 'INHAMBANE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-160', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-161', 'Maxixe', 'INHAMBANE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-161', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false),
  ('mz-branch-162', 'Ungwana', 'INHAMBANE', 'Mozambique', '', '', 'Catandica District, Mozambique', '', '0', 'J5-MZ-162', 'Live', '2026', 'Imported from Mozambique Branches.xls - April 2026', false)
on conflict (id) do update set
  name = excluded.name,
  province = excluded.province,
  country = excluded.country,
  prophet = excluded.prophet,
  phone = excluded.phone,
  address = excluded.address,
  gps = excluded.gps,
  members = excluded.members,
  code = excluded.code,
  status = excluded.status,
  founded = excluded.founded,
  notes = excluded.notes,
  is_hq = excluded.is_hq;
